# Generated by Django 6.0.3 on 2026-03-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('evento_trigger', models.CharField(max_length=100, unique=True)),
                ('template_subject', models.CharField(max_length=255)),
                ('template_body', models.TextField()),
                ('invia_email', models.BooleanField(default=True)),
                ('destinatario', models.CharField(choices=[('dipendente', 'Al dipendente'), ('manager', 'Al manager'), ('hr', 'All HR'), ('admin', 'All admin')], default='dipendente', max_length=50)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Notifica',
                'verbose_name_plural': 'Tipi Notifica',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinatario', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_invio', models.DateTimeField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('pending', 'In coda'), ('sent', 'Inviata'), ('failed', 'Errore')], default='pending', max_length=20)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.azienda')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifiche_email.tiponotifica')),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
