# Generated by Django 6.0.3 on 2026-03-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0002_alter_documento_caricato_da'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-data_caricamento'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AddField(
            model_name='documento',
            name='caricato_dal_dipendente',
            field=models.BooleanField(default=False, verbose_name='Caricato dal dipendente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='descrizione',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrizione / Titolo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('contratto', 'Contratto di lavoro'), ('privacy', 'Autorizzazione privacy'), ('busta_paga', 'Busta paga'), ('certificato', 'CUD / Certificato fiscale'), ('carichi_famiglia', 'Comunicazione carichi di famiglia'), ('documento_identita', 'Documento di identità'), ('permesso_soggiorno', 'Permesso di soggiorno'), ('codice_fiscale_doc', 'Tessera sanitaria / Codice fiscale'), ('attestato', 'Attestato professionale'), ('certificazione', 'Certificazione / Titolo di studio'), ('altro', 'Altro')], max_length=30, verbose_name='Tipo documento'),
        ),
    ]
