# Logging robusto per produzione
import json
import os
# In produzione tipicamente /var/www/logs; in locale cartella `logs/` nel progetto (sempre scrivibile).
if os.path.isdir('/var/www/logs'):
	LOG_DIR = '/var/www/logs'
else:
	LOG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'logs')
os.makedirs(LOG_DIR, mode=0o755, exist_ok=True)
LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'verbose': {
			'format': '[{asctime}] {levelname} {name} {message}',
			'style': '{',
		},
	},
	'handlers': {
		'file': {
			'level': 'DEBUG',
			'class': 'logging.FileHandler',
			'filename': os.path.join(LOG_DIR, 'gesper.log'),
			'formatter': 'verbose',
		},
		'console': {
			'level': 'ERROR',
			'class': 'logging.StreamHandler',
			'formatter': 'verbose',
		},
	},
	'root': {
		'handlers': ['file', 'console'],
		'level': 'ERROR',
	},
	'loggers': {
		'django': {
			'handlers': ['file', 'console'],
			'level': 'DEBUG',
			'propagate': True,
		},
	},
}
# URL di login per il decoratore @login_required
LOGIN_URL = '/accounts/login/'

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
# Percorso assoluto per la raccolta dei file statici in produzione
STATIC_ROOT = '/var/www/gesper/staticfiles'


# Configurazione esplicita sessioni
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'gesper_sessionid'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # False per HTTP (non HTTPS)
SESSION_COOKIE_DOMAIN = None  # None per accettare qualsiasi dominio
# Durata sessione: 8 ore
SESSION_COOKIE_AGE = 8 * 60 * 60  # 8 ore
# Non scadere alla chiusura browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# Aggiorna la scadenza ad ogni richiesta
SESSION_SAVE_EVERY_REQUEST = True

# Vista personalizzata per errori CSRF (token scaduto)
CSRF_FAILURE_VIEW = 'views.csrf_failure'

# Configurazione CSRF per supportare localhost e 0.0.0.0
CSRF_TRUSTED_ORIGINS = [
	'https://gesper1.plazapretoria.it',
	'https://gesper.plazapretoria.it',
	'https://www.gesper.plazapretoria.it',
	'https://www.plazapretoria.it',
	'https://plazapretoria.it',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8001',
    'http://127.0.0.1:8001',
    'http://0.0.0.0:8000',
    'https://alberto-smilacaceous-audria.ngrok-free.dev',
    'https://glossary-adoption-namespace-laptop.trycloudflare.com',
]
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = 'gesper_csrftoken'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False  # False per HTTP
CSRF_COOKIE_DOMAIN = None  # None per accettare qualsiasi dominio
CSRF_USE_SESSIONS = False  # Usa cookie separato per CSRF

# Quando l'app è dietro reverse proxy (nginx), usa gli header forwarded
# per riconoscere correttamente richieste HTTPS/host reale.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Logging di test all'avvio
import logging
logging.getLogger('django').debug('GESPER: logging file attivo (DEBUG)')
"""
Django settings for gesper project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# ── Load environment variables from .env file (if exists) ──
env_file = Path(__file__).resolve().parent / '.env'
if env_file.exists():
	for line in env_file.read_text().splitlines():
		if line.strip() and not line.startswith('#'):
			key, val = line.split('=', 1)
			os.environ.setdefault(key.strip(), val.strip())

# Cartella progetto: dove stanno manage.py, settings.py, templates/, documenti/, …
BASE_DIR = Path(__file__).resolve().parent
# Layout XAMPP tipico: htdocs/gesper/ → genitore = htdocs (DB/media storici possono stare lì)
_HTDOCS_PARENT = BASE_DIR.parent

# Radice dati persistenti (DB SQLite, media upload, cartella archivio/dump): default `documento/` nel progetto.
# In produzione: es. GESPER_DATA_ROOT=/var/www/documento (vedi settings_production + Nginx alias media).
_env_data_root = os.environ.get('GESPER_DATA_ROOT', '').strip()
GESPER_DATA_ROOT = (
	Path(_env_data_root).expanduser().resolve()
	if _env_data_root
	else (BASE_DIR / 'documento')
)
_arch_sub = os.environ.get('GESPER_ARCHIVIO_SUBDIR', 'archivio').strip().strip('/') or 'archivio'
GESPER_ARCHIVIO_ROOT = GESPER_DATA_ROOT / _arch_sub

# Static files directories
STATICFILES_DIRS = [BASE_DIR / 'static']
# Versione asset JS proposta (cache-busting). Override via env: GESPER_PROPOSTA_JS_VERSION
PROPOSTA_JS_VERSION = os.environ.get('GESPER_PROPOSTA_JS_VERSION', '2026-04-15-2').strip() or '2026-04-15-2'

# Media: override esplicito, altrimenti priorità installazioni esistenti (htdocs → progetto) poi `documento/media`.
MEDIA_URL = '/media/'
_env_media_root = os.environ.get('GESPER_MEDIA_ROOT', '').strip()
if _env_media_root:
	MEDIA_ROOT = Path(_env_media_root).expanduser().resolve()
else:
	_data_media = GESPER_DATA_ROOT / 'media'
	_htdocs_media = _HTDOCS_PARENT / 'media'
	_base_media = BASE_DIR / 'media'
	if _htdocs_media.is_dir():
		MEDIA_ROOT = _htdocs_media
	elif _base_media.is_dir():
		MEDIA_ROOT = _base_media
	else:
		MEDIA_ROOT = _data_media

# Sotto MEDIA_ROOT: cartella default per tipi non mappati (contratti, privacy, identità, …).
# Override: GESPER_DOCUMENTI_SUBDIR=altro_nome
_DOC_SUB = os.environ.get('GESPER_DOCUMENTI_SUBDIR', 'varie').strip().strip('/')
DOCUMENTI_MEDIA_SUBDIR = _DOC_SUB or 'varie'

# Sottocartelle per tipo (sotto MEDIA_ROOT, senza prefisso documenti/ — layout piatto).
# Override: GESPER_DOCUMENTO_TIPO_MEDIA_SUBDIRS_JSON
DOCUMENTO_TIPO_MEDIA_SUBDIRS = {
	# Core payroll / fiscale
	'busta_paga': 'buste_paghe',
	'certificato': 'cud',
	'altro': 'f24',
	'unilav': 'unilav',
	'riepilogo_mensile': 'riepiloghi_mensili',
	# Contrattualistica / HR
	'contratto': 'contratti',
	'privacy': 'privacy',
	'carichi_famiglia': 'carichi_famiglia',
	# Identita / anagrafica
	'documento_identita': 'documenti_identita',
	'permesso_soggiorno': 'permessi_soggiorno',
	'codice_fiscale_doc': 'codici_fiscali',
	# Professionale
	'curriculum': 'curriculum',
	'attestato': 'attestati',
	'abilitazione': 'abilitazioni',
	'titolo_studio': 'titoli_studio',
	'certificazione': 'certificazioni',
}
_doc_tipo_sub_json = os.environ.get('GESPER_DOCUMENTO_TIPO_MEDIA_SUBDIRS_JSON', '').strip()
if _doc_tipo_sub_json:
	try:
		_merged = json.loads(_doc_tipo_sub_json)
		if isinstance(_merged, dict):
			DOCUMENTO_TIPO_MEDIA_SUBDIRS = {**DOCUMENTO_TIPO_MEDIA_SUBDIRS, **_merged}
	except json.JSONDecodeError:
		pass

# PDF busta paga cifrati: oltre alla password studio predefinita (DOLCEMASCOLO) si possono
# aggiungere altre stringhe, provate in sequenza. Esempio .env:
#   GESPER_BUSTE_PDF_PASSWORDS=altraPassword,seconda
_extra_buste_pw = os.environ.get('GESPER_BUSTE_PDF_PASSWORDS', '').strip()
BUSTE_PAGA_PDF_PASSWORDS = (
	[p.strip() for p in _extra_buste_pw.split(',') if p.strip()]
	if _extra_buste_pw
	else []
)


def _sqlite_database_path() -> Path:
	"""Percorso DB SQLite.

	Ordine:
	1) GESPER_SQLITE_PATH se impostata.
	2) gesper/db.sqlite3 se esiste (dev / VPS legacy nel repo).
	3) documento/db.sqlite3 (GESPER_DATA_ROOT) se esiste.
	4) htdocs/db.sqlite3 se esiste (XAMPP vecchio).
	5) Nuovo database: documento/db.sqlite3 (stessa radice di media/archivio).

	Nota: usare il file sotto htdocs mentre il server gira in sandbox / permessi limitati
	causa spesso *attempt to write a readonly database* (sessioni Django incluse).
	"""
	env = os.environ.get('GESPER_SQLITE_PATH')
	if env:
		return Path(env).expanduser().resolve()
	base = BASE_DIR / 'db.sqlite3'
	data_db = GESPER_DATA_ROOT / 'db.sqlite3'
	legacy = _HTDOCS_PARENT / 'db.sqlite3'
	if base.exists():
		return base
	if data_db.exists():
		return data_db
	if legacy.exists():
		return legacy
	return data_db


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zgjrv5l#%-cuz^0t*-e&-)*z#0-#5xpc(d+z7y$5m958gj#+fw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
	'accounts.apps.AccountsConfig',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.humanize',
	'anagrafiche',
	'presenze',
	'documenti.apps.DocumentiConfig',
	'richieste',

	'log_attivita',
	'rapporto_di_lavoro',
	'workflow',
	'notifiche_email',
	'storico',
	'guida',

	'api',
	'rest_framework',
	'rest_framework_simplejwt',
]

REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'rest_framework_simplejwt.authentication.JWTAuthentication',
	),
	'DEFAULT_PERMISSION_CLASSES': (
		'rest_framework.permissions.IsAuthenticated',
	),
}

from datetime import timedelta
SIMPLE_JWT = {
	'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=15),
	'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
	'ROTATE_REFRESH_TOKENS':  True,
}

# VAPID keys per Web Push Notifications
VAPID_PUBLIC_KEY  = 'BI70toPKOU9ehMBNL3VQ-1Y2nPkTGep522gwyFooLmGl7MsgC5vbnAZjtYLa_aHHiMDstiDq36CT_r-hoKfVurw'
VAPID_PRIVATE_KEY = """-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIKcJtDT2lMKz4Wbmr/m0iONOQ4JIFhmK8FSs/zFPTlkroAoGCCqGSM49
AwEHoUQDQgAEjvS2g8o5T16EwE0vdVD7Vjac+RMZ6nnbaDDIWiguYaXsyyALm9uc
BmO1gtr9oceIwOy2IOrfoJP+v6Ggp9W6vA==
-----END EC PRIVATE KEY-----"""
VAPID_CLAIMS_EMAIL = 'admin@gesper.local'

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.locale.LocaleMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'log_attivita.middleware.GesperErrorMiddleware',
]

# Stesso host: la PWA (es. /gesper-app/) può incorporare il portale in iframe.
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [BASE_DIR / 'templates'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.request',
				'django.template.context_processors.i18n',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'accounts.context_processors.config_sistema',
				'accounts.context_processors.gesper_browser_paths',
				'accounts.context_processors.gesper_pwa_embed',
				'accounts.context_processors.consulente_recesso_prova_nav',
			],
		},
	},
]

# Modello utente personalizzato
AUTH_USER_MODEL = 'accounts.User'
WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': _sqlite_database_path(),
	}
}


# Password validation — profilo elevato (include validator custom per candidati)
AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
		'OPTIONS': {'min_length': 12},
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
	{
		# Validatore custom: maiuscole + minuscole + cifre + caratteri speciali
		'NAME': 'accounts.validators.PasswordForteValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
#
# Date in DB: sempre DateField/DateTimeField (valore Python; SQLite/PostgreSQL in forma ISO).
# Visualizzazione UI: gg/mm/aaaa tramite formats/it + filtri |date:"d/m/Y" / |it_date / |num_it / |euro_it
# (vedi docs/CONVENZIONI_FORMATO.md).

LANGUAGE_CODE = 'it'

LOCALE_PATHS = [
	p
	for p in (BASE_DIR / 'locale', _HTDOCS_PARENT / 'locale')
	if p.is_dir()
]

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_L10N = True  # Abilita localizzazione numeri/date

USE_TZ = True

# Override formati italiani (date compatte gg/mm/aaaa, numeri)
FORMAT_MODULE_PATH = ['formats']

# Form modelli Django: gg/mm/aaaa + varianti + ISO (type="date" / API)
DATE_INPUT_FORMATS = [
	'%d/%m/%Y',
	'%d/%m/%y',
	'%d-%m-%Y',
	'%d-%m-%y',
	'%Y-%m-%d',
]

# Formattazione numeri in template con localize / number_format
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3

# ── E-mail ──────────────────────────────────────────────────────
# Configurazione SMTP: legge credenziali da variabili d'ambiente per sicurezza
# Se non presenti, usa valori di fallback per sviluppo locale
import os

EMAIL_BACKEND       = os.environ.get(
	'EMAIL_BACKEND',
	'accounts.email_backend.ConfigurazioneSistemaEmailBackend',
)
EMAIL_HOST          = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT          = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS       = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL       = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER', 'rosario.dolcemascolo@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ── Redirect post-login ─────────────────────────────────────────
LOGIN_REDIRECT_URL = '/accounts/profile/'

# ── Cache (OTP registrazione, rate limit) ─────────────────────
# Produzione multi-worker: impostare GESPER_REDIS_URL=redis://127.0.0.1:6379/1
_redis_url = os.environ.get('GESPER_REDIS_URL', '').strip()
if _redis_url:
	CACHES = {
		'default': {
			'BACKEND': 'django.core.cache.backends.redis.RedisCache',
			'LOCATION': _redis_url,
		}
	}
else:
	CACHES = {
		'default': {
			'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
			'LOCATION': 'gesper-otp',
		}
	}

# ── Web Push: chiavi da env in produzione (override) ───────────
_vapid_pub = os.environ.get('GESPER_VAPID_PUBLIC_KEY', '').strip()
_vapid_priv = os.environ.get('GESPER_VAPID_PRIVATE_KEY', '').strip()
if _vapid_pub:
	VAPID_PUBLIC_KEY = _vapid_pub
if _vapid_priv:
	VAPID_PRIVATE_KEY = _vapid_priv
if os.environ.get('GESPER_VAPID_EMAIL', '').strip():
	VAPID_CLAIMS_EMAIL = os.environ.get('GESPER_VAPID_EMAIL', '').strip()
