# Generated by Django 6.0.3 on 2026-03-05 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('ora_entrata', models.TimeField(verbose_name='Ora entrata')),
                ('ora_uscita', models.TimeField(blank=True, null=True, verbose_name='Ora uscita')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('data_registrazione', models.DateTimeField(auto_now_add=True, verbose_name='Data registrazione')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.azienda', verbose_name='Azienda')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.dipendente', verbose_name='Dipendente')),
                ('registrata_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.user', verbose_name='Registrata da')),
            ],
            options={
                'verbose_name': 'Presenza',
                'verbose_name_plural': 'Presenze',
            },
        ),
    ]
