# Generated by Django 6.0.3 on 2026-03-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0004_dipendente_candidato_fields'),
        ('presenze', '0002_alter_presenza_registrata_da'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenza',
            options={'ordering': ['data'], 'verbose_name': 'Presenza', 'verbose_name_plural': 'Presenze'},
        ),
        migrations.AddField(
            model_name='presenza',
            name='causale',
            field=models.CharField(choices=[('P', 'Presenza'), ('ST', 'Straordinario'), ('F', 'Ferie'), ('PE', 'Permesso'), ('M', 'Malattia'), ('INF', 'Infortunio'), ('MAT', 'Maternità / Paternità'), ('CIG', 'Cassa Integrazione'), ('A', 'Assenza ingiustificata'), ('FE', 'Festivo lavorato'), ('R', 'Riposo / Giorno libero'), ('SMART', 'Smart working'), ('ALTRO', 'Altro')], default='P', max_length=10, verbose_name='Causale'),
        ),
        migrations.AddField(
            model_name='presenza',
            name='data_modifica',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima modifica'),
        ),
        migrations.AddField(
            model_name='presenza',
            name='ore_straordinario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Ore straordinario'),
        ),
        migrations.AlterField(
            model_name='presenza',
            name='dipendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenze', to='anagrafiche.dipendente', verbose_name='Dipendente'),
        ),
        migrations.AlterField(
            model_name='presenza',
            name='ora_entrata',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora entrata'),
        ),
        migrations.AlterUniqueTogether(
            name='presenza',
            unique_together={('dipendente', 'data')},
        ),
    ]
