# Generated by Django 6.0.3 on 2026-03-19 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _default_schedule():
    return {
        str(i): {
            'attivo':   i < 5,
            'entrata':  '09:00' if i < 5 else None,
            'uscita':   '17:00' if i < 5 else None,
            'causale':  'P'     if i < 5 else 'R',
            'doppio':   False,
            'entrata2': None,
            'uscita2':  None,
        }
        for i in range(7)
    }


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0004_dipendente_candidato_fields'),
        ('presenze', '0003_alter_presenza_options_presenza_causale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoLavorativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome turno')),
                ('data_inizio', models.DateField(verbose_name='Valido dal')),
                ('data_fine', models.DateField(blank=True, null=True, verbose_name='Valido fino al')),
                ('schedule', models.JSONField(default=_default_schedule, verbose_name='Orario settimanale')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.azienda', verbose_name='Azienda')),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turni', to='anagrafiche.dipendente', verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Turno lavorativo',
                'verbose_name_plural': 'Turni lavorativi',
                'ordering': ['dipendente', 'data_inizio'],
            },
        ),
    ]
