# Generated by Django 6.0.3 on 2026-03-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0004_turno_lavorativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenza',
            name='ora_entrata2',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora entrata 2°'),
        ),
        migrations.AddField(
            model_name='presenza',
            name='ora_uscita2',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora uscita 2°'),
        ),
    ]
