# Generated by Django 6.0.3 on 2026-03-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0005_doppio_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenza',
            name='ora_entrata3',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora entrata 3°'),
        ),
        migrations.AddField(
            model_name='presenza',
            name='ora_uscita3',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora uscita 3°'),
        ),
    ]
