# Generated by Django 6.0.3 on 2026-03-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0008_presenza_tipo_straordinario_riepilogomensilepresenze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riepilogomensilepresenze',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
