# Generated by Django 6.0.3 on 2026-04-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0006_azienda_sede_lavorativa_indirizzo_and_more'),
        ('presenze', '0009_alter_riepilogomensilepresenze_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneOrarioAnnuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(verbose_name='Anno')),
                ('giorni_riposo_settimanale', models.JSONField(default=list, help_text='Lista interi 0=Lun ... 6=Dom', verbose_name='Giorni riposo settimanale')),
                ('genera_presenze_teoriche', models.BooleanField(default=True, verbose_name='Genera presenze teoriche di default')),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurazioni_orario_annuali', to='anagrafiche.azienda', verbose_name='Azienda')),
            ],
            options={
                'verbose_name': 'Configurazione orario annuale',
                'verbose_name_plural': 'Configurazioni orario annuali',
                'ordering': ['-anno', 'azienda__nome'],
                'unique_together': {('azienda', 'anno')},
            },
        ),
        migrations.CreateModel(
            name='TurnoLavorativoAziendale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome turno')),
                ('ora_inizio', models.TimeField(verbose_name='Inizio turno')),
                ('ora_fine', models.TimeField(verbose_name='Fine turno')),
                ('ordine', models.PositiveSmallIntegerField(default=1, verbose_name='Ordine')),
                ('attivo', models.BooleanField(default=True)),
                ('configurazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turni_lavorativi', to='presenze.configurazioneorarioannuale', verbose_name='Configurazione annuale')),
            ],
            options={
                'verbose_name': 'Turno lavorativo aziendale',
                'verbose_name_plural': 'Turni lavorativi aziendali',
                'ordering': ['ordine', 'ora_inizio'],
            },
        ),
        migrations.CreateModel(
            name='AssegnazioneTurnoDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField(verbose_name='Dal')),
                ('data_fine', models.DateField(blank=True, null=True, verbose_name='Al')),
                ('attivo', models.BooleanField(default=True)),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni_turno', to='anagrafiche.dipendente')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='presenze.turnolavorativoaziendale')),
            ],
            options={
                'verbose_name': 'Assegnazione turno dipendente',
                'verbose_name_plural': 'Assegnazioni turni dipendenti',
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='FasciaAperturaSettimanale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_settimana', models.PositiveSmallIntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')])),
                ('chiuso', models.BooleanField(default=False, verbose_name='Chiuso')),
                ('ora_apertura', models.TimeField(blank=True, null=True, verbose_name='Apertura')),
                ('ora_chiusura', models.TimeField(blank=True, null=True, verbose_name='Chiusura')),
                ('configurazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasce_apertura', to='presenze.configurazioneorarioannuale', verbose_name='Configurazione annuale')),
            ],
            options={
                'verbose_name': 'Fascia apertura settimanale',
                'verbose_name_plural': 'Fasce apertura settimanali',
                'ordering': ['giorno_settimana'],
                'unique_together': {('configurazione', 'giorno_settimana')},
            },
        ),
    ]
