# Generated by Django 6.0.3 on 2026-04-05 19:42

from django.db import migrations, models


def copia_orari_precedenti_in_mattina(apps, schema_editor):
    Fascia = apps.get_model('presenze', 'FasciaAperturaSettimanale')
    for r in Fascia.objects.all().iterator():
        # I campi legacy sono ancora presenti in questo punto della migration
        apertura = getattr(r, 'ora_apertura', None)
        chiusura = getattr(r, 'ora_chiusura', None)
        update_fields = []
        if apertura and not r.ora_apertura_mattina:
            r.ora_apertura_mattina = apertura
            update_fields.append('ora_apertura_mattina')
        if chiusura and not r.ora_chiusura_mattina:
            r.ora_chiusura_mattina = chiusura
            update_fields.append('ora_chiusura_mattina')
        if update_fields:
            r.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0010_configurazioneorarioannuale_turnolavorativoaziendale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasciaaperturasettimanale',
            name='ora_apertura_mattina',
            field=models.TimeField(blank=True, null=True, verbose_name='Apertura mattina'),
        ),
        migrations.AddField(
            model_name='fasciaaperturasettimanale',
            name='ora_apertura_pomeriggio',
            field=models.TimeField(blank=True, null=True, verbose_name='Apertura pomeriggio'),
        ),
        migrations.AddField(
            model_name='fasciaaperturasettimanale',
            name='ora_chiusura_mattina',
            field=models.TimeField(blank=True, null=True, verbose_name='Chiusura mattina'),
        ),
        migrations.AddField(
            model_name='fasciaaperturasettimanale',
            name='ora_chiusura_pomeriggio',
            field=models.TimeField(blank=True, null=True, verbose_name='Chiusura pomeriggio'),
        ),
        migrations.RunPython(copia_orari_precedenti_in_mattina, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name='fasciaaperturasettimanale',
            name='ora_apertura',
        ),
        migrations.RemoveField(
            model_name='fasciaaperturasettimanale',
            name='ora_chiusura',
        ),
    ]
