# Generated by Django 6.0.3 on 2026-04-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0001_initial'),
        ('presenze', '0011_remove_fasciaaperturasettimanale_ora_apertura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneOrarioMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(verbose_name='Anno')),
                ('mese', models.PositiveSmallIntegerField(choices=[(1, 'Gennaio'), (2, 'Febbraio'), (3, 'Marzo'), (4, 'Aprile'), (5, 'Maggio'), (6, 'Giugno'), (7, 'Luglio'), (8, 'Agosto'), (9, 'Settembre'), (10, 'Ottobre'), (11, 'Novembre'), (12, 'Dicembre')], verbose_name='Mese')),
                ('giorni_riposo_settimanale', models.JSONField(default=list, help_text='Lista interi 0=Lun ... 6=Dom', verbose_name='Giorni riposo settimanale')),
                ('genera_presenze_teoriche', models.BooleanField(default=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurazioni_orario_mensili', to='anagrafiche.azienda', verbose_name='Azienda')),
            ],
            options={
                'verbose_name': 'Configurazione orario mensile',
                'verbose_name_plural': 'Configurazioni orario mensili',
                'ordering': ['-anno', 'mese', 'azienda__nome'],
                'unique_together': {('azienda', 'anno', 'mese')},
            },
        ),
        migrations.CreateModel(
            name='FasciaAperturaMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_settimana', models.PositiveSmallIntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')])) ,
                ('chiuso', models.BooleanField(default=False, verbose_name='Chiuso')),
                ('ora_apertura_mattina', models.TimeField(blank=True, null=True, verbose_name='Apertura mattina')),
                ('ora_chiusura_mattina', models.TimeField(blank=True, null=True, verbose_name='Chiusura mattina')),
                ('ora_apertura_pomeriggio', models.TimeField(blank=True, null=True, verbose_name='Apertura pomeriggio')),
                ('ora_chiusura_pomeriggio', models.TimeField(blank=True, null=True, verbose_name='Chiusura pomeriggio')),
                ('configurazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasce_apertura', to='presenze.configurazioneorariomensile', verbose_name='Configurazione mensile')),
            ],
            options={
                'verbose_name': 'Fascia apertura mensile',
                'verbose_name_plural': 'Fasce apertura mensili',
                'ordering': ['giorno_settimana'],
                'unique_together': {('configurazione', 'giorno_settimana')},
            },
        ),
    ]
