# Generated by Django 6.0.3 on 2026-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenze', '0012_configurazioneorariomensile_fasciaaperturamensile'),
    ]

    operations = [
        migrations.AddField(
            model_name='riepilogomensilepresenze',
            name='ore_straord_domenica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ore straordinario domenicale'),
        ),
        migrations.AlterField(
            model_name='riepilogomensilepresenze',
            name='ore_straord_festivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ore straordinario festivo (non domenica)'),
        ),
    ]
