# Generated by Django 6.0.3 on 2026-04-19 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0008_dipendente_matricola'),
        ('presenze', '0013_riepilogo_ore_straord_domenica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoMonteDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_monte', models.CharField(choices=[('FERIE_GG', 'Ferie (giorni)'), ('ROL_ORE', 'ROL / permessi (ore)'), ('RIPOSI_COMP', 'Riposi compensativi')], max_length=16, verbose_name='Tipo monte')),
                ('anno_competenza', models.PositiveSmallIntegerField(verbose_name='Anno competenza')),
                ('saldo_iniziale', models.DecimalField(decimal_places=2, default=0, help_text='Tipicamente da import ultima busta paga / migrazione.', max_digits=8, verbose_name='Saldo iniziale')),
                ('data_saldo_iniziale', models.DateField(blank=True, null=True, verbose_name='Data riferimento saldo iniziale')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldi_monte_presenze', to='anagrafiche.azienda', verbose_name='Azienda')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldi_monte', to='anagrafiche.dipendente', verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Saldo monte dipendente',
                'verbose_name_plural': 'Saldi monte dipendenti',
                'ordering': ['-anno_competenza', 'dipendente_id', 'tipo_monte'],
                'unique_together': {('dipendente', 'azienda', 'tipo_monte', 'anno_competenza')},
            },
        ),
        migrations.CreateModel(
            name='MovimentoMonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField(verbose_name='Data competenza')),
                ('tipo_movimento', models.CharField(choices=[('MATURAZIONE', 'Maturazione'), ('GODIMENTO', 'Godimento'), ('RETTIFICA_HR', 'Rettifica HR'), ('IMPORT_CONSULENTE', 'Import / consulente'), ('ANNULLAMENTO', 'Annullamento')], max_length=20, verbose_name='Tipo movimento')),
                ('quantita', models.DecimalField(decimal_places=2, help_text='Segno algebrico: + a favore dipendente, − godimento / decurtazione.', max_digits=10, verbose_name='Quantità')),
                ('unita', models.CharField(choices=[('GG', 'Giorni'), ('ORE', 'Ore')], max_length=3, verbose_name='Unità')),
                ('origine', models.CharField(choices=[('PRESENZA', 'Presenza giornaliera'), ('RIEPILOGO_MENSILE', 'Chiusura riepilogo mensile'), ('MANUALE', 'Manuale'), ('IMPORT', 'Import massivo')], default='MANUALE', max_length=20, verbose_name='Origine')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', help_text='Es. "rie-{anno}-{mese}-ferie" per evitare doppi movimenti in chiusura mese.', max_length=80, verbose_name='Chiave idempotenza')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('presenza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_monte', to='presenze.presenza', verbose_name='Presenza collegata')),
                ('registrato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_monte_registrati', to=settings.AUTH_USER_MODEL, verbose_name='Registrato da')),
                ('riepilogo_mensile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_monte', to='presenze.riepilogomensilepresenze', verbose_name='Riepilogo mensile')),
                ('saldo_monte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to='presenze.saldomontedipendente', verbose_name='Saldo monte')),
            ],
            options={
                'verbose_name': 'Movimento monte',
                'verbose_name_plural': 'Movimenti monte',
                'ordering': ['-data_movimento', '-data_creazione'],
                'indexes': [models.Index(fields=['saldo_monte', 'data_movimento'], name='presenze_mo_saldo_m_c60937_idx')],
            },
        ),
    ]
