# Generated by Django 6.0.3 on 2026-04-19 16:26

import django.db.models.deletion
from django.db import migrations, models


def seed_causali_non_maturative(apps, schema_editor):
    C = apps.get_model('presenze', 'CausaleAssenzaNonMaturativa')
    rows = [
        ('A', 'Assenze ingiustificate', 'INTERA', 10),
        ('SOSP', 'Sospensioni disciplinari', 'INTERA', 20),
        ('CIG', 'Cassa integrazione / sospensioni assimilabili', 'INTERA', 30),
        ('ALTRO', 'Aspettativa non retribuita (causale Altro)', 'INTERA', 40),
        ('M', 'Malattia oltre il periodo di comporto (parte eccedente)', 'MALATTIA_ECCEDENTE', 50),
    ]
    for cod, eti, mod, ord in rows:
        if not C.objects.filter(azienda__isnull=True, codice_causale=cod, modalita=mod).exists():
            C.objects.create(
                azienda=None,
                codice_causale=cod,
                etichetta=eti,
                modalita=mod,
                ordine=ord,
                attiva=True,
            )


def unseed_causali_non_maturative(apps, schema_editor):
    C = apps.get_model('presenze', 'CausaleAssenzaNonMaturativa')
    C.objects.filter(azienda__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0008_dipendente_matricola'),
        ('presenze', '0014_saldo_movimento_monte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenza',
            name='causale',
            field=models.CharField(choices=[('P', 'Presenza'), ('ST', 'Straordinario'), ('F', 'Ferie'), ('PE', 'Permesso'), ('M', 'Malattia'), ('INF', 'Infortunio'), ('MAT', 'Maternità / Paternità'), ('CIG', 'Cassa Integrazione'), ('A', 'Assenza ingiustificata'), ('FE', 'Festivo lavorato'), ('R', 'Riposo / Giorno libero'), ('SMART', 'Smart working'), ('ALTRO', 'Altro'), ('SOSP', 'Sospensione disciplinare')], default='P', max_length=10, verbose_name='Causale'),
        ),
        migrations.CreateModel(
            name='CausaleAssenzaNonMaturativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_causale', models.CharField(help_text='Codice come in Presenza (es. A, M, CIG, ALTRO, SOSP)', max_length=10, verbose_name='Causale')),
                ('etichetta', models.CharField(max_length=200, verbose_name='Descrizione')),
                ('modalita', models.CharField(choices=[('INTERA', 'Giornata intera non maturativa'), ('MALATTIA_ECCEDENTE', 'Malattia oltre il periodo di comporto (solo parte eccedente, ordine annuo)')], default='INTERA', max_length=32, verbose_name='Modalità conteggio')),
                ('attiva', models.BooleanField(default=True)),
                ('ordine', models.PositiveSmallIntegerField(default=0, verbose_name='Ordine')),
                ('azienda', models.ForeignKey(blank=True, help_text='Vuoto = default per tutte le aziende', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='causali_non_maturative', to='anagrafiche.azienda', verbose_name='Azienda')),
            ],
            options={
                'verbose_name': 'Causale assenza non maturativa',
                'verbose_name_plural': 'Causali assenze non maturative',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.RunPython(seed_causali_non_maturative, unseed_causali_non_maturative),
    ]
