# Generated by Django 6.0.3 on 2026-03-05 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAttivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operazione', models.CharField(choices=[('login', 'Accesso'), ('logout', 'Uscita'), ('upload_doc', 'Caricamento documento'), ('download_doc', 'Download documento'), ('modifica_anagrafica', 'Modifica anagrafica'), ('richiesta', 'Richiesta ferie/permesso/malattia'), ('presenza', 'Registrazione presenza'), ('altro', 'Altro')], max_length=30)),
                ('descrizione', models.TextField(blank=True)),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('oggetto_id', models.CharField(blank=True, max_length=100)),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.azienda')),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
