# Generated by Django 6.0.3 on 2026-03-18 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0004_dipendente_candidato_fields'),
        ('log_attivita', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogErrore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('livello', models.CharField(choices=[('warning', 'Warning'), ('error', 'Errore'), ('critical', 'Critico')], default='error', max_length=10)),
                ('messaggio', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('risolto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Log errore',
                'verbose_name_plural': 'Log errori',
                'ordering': ['-data_ora'],
            },
        ),
        migrations.AlterModelOptions(
            name='logattivita',
            options={'ordering': ['-data_ora'], 'verbose_name': 'Log attività', 'verbose_name_plural': 'Log attività'},
        ),
        migrations.AddField(
            model_name='logattivita',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logattivita',
            name='azienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.azienda'),
        ),
        migrations.AlterField(
            model_name='logattivita',
            name='operazione',
            field=models.CharField(choices=[('login', 'Accesso'), ('logout', 'Uscita'), ('login_fallito', 'Accesso fallito'), ('registrazione', 'Registrazione candidato'), ('verifica_email', 'Verifica e-mail'), ('completa_profilo', 'Completamento profilo'), ('candidatura', 'Espressione interesse'), ('convalida', 'Convalida candidato'), ('revoca_convalida', 'Revoca convalida'), ('upload_doc', 'Caricamento documento'), ('download_doc', 'Download documento'), ('modifica_anagrafica', 'Modifica anagrafica'), ('crea_proposta', 'Creazione proposta'), ('modifica_proposta', 'Modifica proposta'), ('assegna_proposta', 'Assegnazione proposta'), ('richiesta', 'Richiesta ferie/permesso/malattia'), ('presenza', 'Registrazione presenza'), ('impostazioni', 'Modifica impostazioni'), ('altro', 'Altro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='logattivita',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='logattivita',
            index=models.Index(fields=['data_ora'], name='log_attivit_data_or_ac30f2_idx'),
        ),
        migrations.AddIndex(
            model_name='logattivita',
            index=models.Index(fields=['utente', 'data_ora'], name='log_attivit_utente__b7aeca_idx'),
        ),
        migrations.AddIndex(
            model_name='logattivita',
            index=models.Index(fields=['operazione'], name='log_attivit_operazi_874de9_idx'),
        ),
        migrations.AddField(
            model_name='logerrore',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_errori', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='logerrore',
            index=models.Index(fields=['data_ora'], name='log_attivit_data_or_8b9dab_idx'),
        ),
        migrations.AddIndex(
            model_name='logerrore',
            index=models.Index(fields=['livello', 'risolto'], name='log_attivit_livello_9dd33a_idx'),
        ),
    ]
