# Generated by Django 6.0.3 on 2026-03-05 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('anagrafiche', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='azienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_users', to='anagrafiche.azienda', verbose_name='Azienda'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Gruppi a cui appartiene l’utente.', related_name='accounts_users', to='auth.group', verbose_name='Gruppi'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permessi specifici per questo utente.', related_name='accounts_users_permissions', to='auth.permission', verbose_name='Permessi utente'),
        ),
    ]
