# Generated by Django 6.0.3 on 2026-03-18 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('anagrafiche', '0004_dipendente_candidato_fields'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Token verifica e-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_token_scadenza',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scadenza token verifica'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verificata',
            field=models.BooleanField(default=False, verbose_name='E-mail verificata'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text="Gruppi a cui appartiene l'utente.", related_name='accounts_users', to='auth.group', verbose_name='Gruppi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ruolo',
            field=models.CharField(choices=[('admin', 'Amministratore'), ('hr', 'Risorse Umane'), ('dipendente', 'Dipendente'), ('consulente', 'Consulente'), ('candidato', 'Candidato')], default='dipendente', max_length=50, verbose_name='Ruolo'),
        ),
        migrations.CreateModel(
            name='ProfiloCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, verbose_name='Codice Fiscale')),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('luogo_nascita', models.CharField(blank=True, max_length=100, verbose_name='Luogo di nascita')),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschile'), ('F', 'Femminile'), ('A', 'Preferisco non specificare')], max_length=1, verbose_name='Sesso')),
                ('nazionalita', models.CharField(blank=True, default='Italiana', max_length=60, verbose_name='Nazionalità')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo di residenza')),
                ('cap', models.CharField(blank=True, max_length=5, verbose_name='CAP')),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('provincia', models.CharField(blank=True, max_length=2, verbose_name='Provincia (sigla)')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('tipo_documento', models.CharField(blank=True, choices=[('ci', "Carta d'identità"), ('passaporto', 'Passaporto'), ('patente', 'Patente di guida'), ('ps', 'Permesso di soggiorno')], max_length=20, verbose_name='Tipo documento')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='Numero documento')),
                ('scadenza_documento', models.DateField(blank=True, null=True, verbose_name='Scadenza documento')),
                ('data_disponibilita', models.DateField(blank=True, null=True, verbose_name='Disponibile dal')),
                ('tipo_rapporto_preferito', models.CharField(blank=True, choices=[('indeterminato', 'Tempo indeterminato'), ('determinato', 'Tempo determinato'), ('entrambi', 'Nessuna preferenza')], default='entrambi', max_length=20, verbose_name='Tipo rapporto preferito')),
                ('ore_settimanali_preferite', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Ore settimanali preferite')),
                ('livello_aspirato', models.CharField(blank=True, max_length=10, verbose_name='Livello CCNL aspirato')),
                ('note_candidatura', models.TextField(blank=True, verbose_name='Note / lettera di presentazione')),
                ('consenso_conservazione', models.BooleanField(default=False, help_text='Autorizza la conservazione del profilo per future selezioni per un periodo massimo di 12 mesi dalla data di iscrizione.', verbose_name='Consenso conservazione profilo (12 mesi)')),
                ('consenso_comunicazione', models.BooleanField(default=False, help_text='Autorizza la comunicazione dei dati a società del gruppo o partner per finalità di selezione del personale.', verbose_name='Consenso comunicazione a terzi')),
                ('data_consensi', models.DateTimeField(blank=True, null=True, verbose_name='Data registrazione consensi')),
                ('profilo_completato', models.BooleanField(default=False, verbose_name='Profilo completato')),
                ('data_completamento', models.DateTimeField(blank=True, null=True, verbose_name='Data completamento profilo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data registrazione')),
                ('azienda_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidati', to='anagrafiche.azienda', verbose_name='Azienda di interesse')),
                ('dipendente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profilo_candidato', to='anagrafiche.dipendente', verbose_name='Dipendente collegato')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo_candidato', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Profilo candidato',
                'verbose_name_plural': 'Profili candidati',
            },
        ),
    ]
