# Generated by Django 6.0.3 on 2026-03-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_token_user_email_token_scadenza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sito', models.CharField(default='GESPER', max_length=100, verbose_name='Nome del sito')),
                ('nome_azienda', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome azienda (intestazione documenti)')),
                ('indirizzo_sede', models.CharField(blank=True, default='', max_length=255, verbose_name='Indirizzo sede legale')),
                ('partita_iva', models.CharField(blank=True, default='', max_length=20, verbose_name='Partita IVA')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='Host SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='Porta SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usa TLS')),
                ('smtp_user', models.CharField(blank=True, default='', help_text='Es. noreply@tuodominio.com oppure account Gmail', max_length=200, verbose_name='Utente SMTP (indirizzo e-mail mittente)')),
                ('smtp_password', models.CharField(blank=True, default='', help_text='Per Gmail: usa una "Password per le app" (16 caratteri)', max_length=200, verbose_name='Password SMTP')),
                ('email_mittente_nome', models.CharField(blank=True, default='', help_text='Es. "GESPER - Gestione Personale". Lascia vuoto per usare solo l\'indirizzo.', max_length=100, verbose_name='Nome mittente e-mail')),
                ('email_notifiche_hr', models.CharField(blank=True, default='', help_text='Indirizzo che riceve le notifiche interne (nuovi candidati, ecc.)', max_length=200, verbose_name='E-mail notifiche HR')),
                ('colore_primario', models.CharField(default='#1b3a5f', help_text='Formato esadecimale, es. #1b3a5f', max_length=7, verbose_name='Colore primario (navbar, titoli)')),
                ('colore_accent', models.CharField(default='#2d6199', help_text='Formato esadecimale, es. #2d6199', max_length=7, verbose_name='Colore accent (bottoni, link)')),
                ('colore_sfondo', models.CharField(default='#f1f4f8', help_text='Formato esadecimale, es. #f1f4f8', max_length=7, verbose_name='Colore sfondo pagina')),
                ('font_famiglia', models.CharField(choices=[('system', 'Sistema (default)'), ('inter', 'Inter'), ('roboto', 'Roboto'), ('open-sans', 'Open Sans'), ('lato', 'Lato'), ('source-sans', 'Source Sans 3')], default='system', max_length=30, verbose_name='Famiglia font')),
                ('font_dimensione_base', models.CharField(choices=[('12', '12px — Compatto'), ('13', '13px — Piccolo'), ('14', '14px — Standard'), ('15', '15px — Leggibile'), ('16', '16px — Grande')], default='14', max_length=4, verbose_name='Dimensione font base')),
            ],
            options={
                'verbose_name': 'Configurazione di sistema',
                'verbose_name_plural': 'Configurazione di sistema',
            },
        ),
    ]
