# Generated by Django 6.0.3 on 2026-03-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_configurazionesistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilocandidato',
            name='competenze',
            field=models.TextField(blank=True, help_text='Elenca le competenze professionali certificate e non (lingue, patenti, corsi, ecc.)', verbose_name='Competenze'),
        ),
        migrations.AddField(
            model_name='profilocandidato',
            name='data_emissione_documento',
            field=models.DateField(blank=True, null=True, verbose_name='Data emissione documento'),
        ),
        migrations.AddField(
            model_name='profilocandidato',
            name='dettaglio_familiari',
            field=models.TextField(blank=True, help_text='Es. coniuge, 2 figli minori, ecc.', verbose_name='Dettaglio familiari a carico'),
        ),
        migrations.AddField(
            model_name='profilocandidato',
            name='dichiarazione_no_condanne',
            field=models.BooleanField(default=False, help_text='Dichiaro di non aver riportato condanne penali e di non essere interessato da procedimenti giudiziari in corso.', verbose_name='Dichiarazione assenza condanne penali'),
        ),
        migrations.AddField(
            model_name='profilocandidato',
            name='file_codice_fiscale',
            field=models.FileField(blank=True, null=True, upload_to='candidati/cf/', verbose_name='Copia tessera sanitaria / Codice fiscale (PDF/JPG)'),
        ),
        migrations.AddField(
            model_name='profilocandidato',
            name='file_documento',
            field=models.FileField(blank=True, null=True, upload_to='candidati/documenti/', verbose_name='Copia documento identità (PDF/JPG)'),
        ),
        migrations.AddField(
            model_name='profilocandidato',
            name='iban',
            field=models.CharField(blank=True, help_text='Es. IT60X0542811101000000123456', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='profilocandidato',
            name='mansione_aspirata',
            field=models.CharField(blank=True, help_text='Es. Cuoco, Cameriere, Barista, Receptionist...', max_length=100, verbose_name='Mansione aspirata'),
        ),
        migrations.AddField(
            model_name='profilocandidato',
            name='num_familiari_a_carico',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Numero familiari a carico'),
        ),
    ]
