# Generated by Django 6.0.3 on 2026-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profilocandidato_competenze_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionesistema',
            name='ultimo_test_email_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data ultimo test e-mail'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='ultimo_test_email_destinatario',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Destinatario ultimo test'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='ultimo_test_email_esito',
            field=models.CharField(blank=True, choices=[('', 'Mai testato'), ('ok', 'Successo'), ('errore', 'Errore')], default='', max_length=10, verbose_name='Esito ultimo test'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='ultimo_test_email_messaggio',
            field=models.TextField(blank=True, default='', verbose_name='Dettaglio ultimo test'),
        ),
    ]
