# Generated by Django 6.0.3 on 2026-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_richiestaintegrazionecandidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ruolo',
                'verbose_name_plural': 'Ruoli',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='ruolo',
        ),
        migrations.AddField(
            model_name='user',
            name='ruoli',
            field=models.ManyToManyField(blank=True, help_text='Ruoli associati all’utente (admin, hr, ecc.)', related_name='utenti', to='accounts.ruolo', verbose_name='Ruoli'),
        ),
    ]
