# Generated by Django 6.0.3 on 2026-04-04 08:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_movimentoimportpaghef24dettaglio'),
        ('documenti', '0005_documento_tipo_nuovi_choices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movimentoimportpaghe',
            new_name='accounts_mo_azienda_d7359e_idx',
            old_name='accounts_mov_azienda__c45c2c_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentoimportpaghe',
            new_name='accounts_mo_azienda_05f7a9_idx',
            old_name='accounts_mov_azienda__1fd687_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentoimportpaghef24dettaglio',
            new_name='accounts_mo_movimen_2c7403_idx',
            old_name='accounts_mov_movimen_f4f4fb_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentoimportpaghef24dettaglio',
            new_name='accounts_mo_codice__983090_idx',
            old_name='accounts_mov_codice__7f3248_idx',
        ),
        migrations.AddField(
            model_name='movimentoimportpaghef24dettaglio',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f24_dettagli', to='documenti.documento', verbose_name='Documento F24 allegato'),
        ),
        migrations.AlterField(
            model_name='movimentoimportpaghe',
            name='importo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Importo (legacy)'),
        ),
    ]
