# Generated by Django 6.0.3 on 2026-04-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_movimentoimportpaghe_natura_busta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movimentoimportpaghe',
            new_name='accounts_mo_azienda_a52f00_idx',
            old_name='accounts_mo_azienda_69f00f_idx',
        ),
    ]
