# Generated by Django 6.0.3 on 2026-04-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_accounts_mo_azienda_69f00f_idx_accounts_mo_azienda_a52f00_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionesistema',
            name='presenze_geo_center_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Usata come default globale se l’azienda non ha coordinate proprie.', max_digits=9, null=True, verbose_name='Latitudine sede (default)'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='presenze_geo_center_lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Usata come default globale se l’azienda non ha coordinate proprie.', max_digits=9, null=True, verbose_name='Longitudine sede (default)'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='presenze_geo_enabled',
            field=models.BooleanField(default=True, verbose_name='Abilita timbratura geolocalizzata'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='presenze_geo_enforce_for_test',
            field=models.BooleanField(default=False, help_text='Se attivo, anche gli utenti in whitelist test devono rispettare GPS/perimetro.', verbose_name='Applica geofence anche agli utenti test'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='presenze_geo_enforce_geofence',
            field=models.BooleanField(default=True, verbose_name='Blocca timbratura fuori perimetro'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='presenze_geo_radius_m',
            field=models.PositiveIntegerField(default=180, verbose_name='Raggio geofence default (metri)'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='presenze_geo_require_gps',
            field=models.BooleanField(default=True, verbose_name='Richiedi GPS per timbratura'),
        ),
    ]
