# Generated by Django 6.0.3 on 2026-04-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_configurazionesistema_presenze_geo_center_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA abilitato'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Segreto TOTP'),
        ),
    ]
