# Generated by Django 6.0.3 on 2026-04-08 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_totp_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiestaintegrazionecandidato',
            name='candidato',
            field=models.ForeignKey(limit_choices_to={'ruoli__codice': 'candidato'}, on_delete=django.db.models.deletion.CASCADE, related_name='richieste_integrazione', to=settings.AUTH_USER_MODEL, verbose_name='Candidato'),
        ),
    ]
