# Generated by Django 6.0.3 on 2026-04-09 05:08

from django.db import migrations

GRUPPO = 'Dipendente — portale self-service'

PERMESSI = (
    ('portale_documenti_personali', 'Portale dipendente: documenti personali'),
    ('portale_buste_paga_cud', 'Portale dipendente: buste paga e CUD'),
    ('portale_presenze_calendario', 'Portale dipendente: presenze e calendario orari'),
    ('portale_richieste', 'Portale dipendente: richieste (ferie, permessi, …)'),
)


def crea_gruppo_e_assegna_utenti(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('accounts', 'User')
    Dipendente = apps.get_model('anagrafiche', 'Dipendente')
    Ruolo = apps.get_model('accounts', 'Ruolo')

    model_name = User._meta.model_name
    ct = ContentType.objects.filter(app_label='accounts', model=model_name).first()
    if ct is None:
        ct, _ = ContentType.objects.get_or_create(
            app_label='accounts',
            model=model_name,
        )
    perm_ids = []
    for codename, name in PERMESSI:
        p, _ = Permission.objects.get_or_create(
            content_type=ct,
            codename=codename,
            defaults={'name': name},
        )
        perm_ids.append(p.pk)

    group, _ = Group.objects.get_or_create(name=GRUPPO)
    group.permissions.set(perm_ids)

    # Utenti con ruolo candidato/dipendente
    for u in User.objects.all():
        if u.ruoli.filter(codice__in=('dipendente', 'candidato')).exists():
            u.groups.add(group)

    # Utenti collegati da anagrafica dipendente
    for dip in Dipendente.objects.exclude(utente=None).select_related('utente'):
        u = dip.utente
        if not getattr(u, 'pk', None):
            continue
        u.groups.add(group)
        stato = getattr(dip, 'stato', '') or ''
        if stato == 'attivo':
            r, _ = Ruolo.objects.get_or_create(
                codice='dipendente', defaults={'nome': 'Dipendente'}
            )
            u.ruoli.add(r)
        elif stato == 'candidato':
            r, _ = Ruolo.objects.get_or_create(
                codice='candidato', defaults={'nome': 'Candidato'}
            )
            u.ruoli.add(r)
        az = getattr(dip, 'azienda_id', None)
        if az and getattr(u, 'azienda_id', None) is None:
            u.azienda_id = az
            u.save(update_fields=['azienda'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_richiestaintegrazionecandidato_candidato'),
        ('anagrafiche', '0006_azienda_sede_lavorativa_indirizzo_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('portale_documenti_personali', 'Portale dipendente: documenti personali'), ('portale_buste_paga_cud', 'Portale dipendente: buste paga e CUD'), ('portale_presenze_calendario', 'Portale dipendente: presenze e calendario orari'), ('portale_richieste', 'Portale dipendente: richieste (ferie, permessi, …)')], 'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
        migrations.RunPython(crea_gruppo_e_assegna_utenti, noop_reverse),
    ]
