# Generated by Django 6.0.3 on 2026-04-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_portale_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionesistema',
            name='sms_abilitato',
            field=models.BooleanField(default=False, verbose_name='Abilita invio SMS'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='sms_http_authorization',
            field=models.CharField(blank=True, default='', help_text='Es. Bearer … oppure Basic …', max_length=400, verbose_name='Header Authorization (opzionale)'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='sms_http_json_template',
            field=models.TextField(blank=True, default='', help_text='JSON con placeholder {telefono} e {testo}. Vuoto = {"to":"{telefono}","text":"{testo}"}', verbose_name='Template corpo JSON (HTTP)'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='sms_http_url',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='URL endpoint SMS (HTTP)'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='sms_prefisso_default',
            field=models.CharField(blank=True, default='+39', help_text='Usato se il numero non inizia con + (es. +39).', max_length=8, verbose_name='Prefisso internazionale default'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('', 'Disattivato'), ('twilio', 'Twilio'), ('http', 'HTTP POST (JSON)')], default='', max_length=20, verbose_name='Provider SMS'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='sms_twilio_account_sid',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Twilio Account SID'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='sms_twilio_auth_token',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Twilio Auth Token'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='sms_twilio_from',
            field=models.CharField(blank=True, default='', help_text='Numero o ID alfanumerico Twilio approvato.', max_length=40, verbose_name='Twilio mittente (From)'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='url_pubblica_base',
            field=models.CharField(blank=True, default='', help_text='Es. https://gesper.plazapretoria.it — usata per costruire link in e-mail/SMS quando la richiesta arriva da localhost. Senza slash finale.', max_length=300, verbose_name='URL pubblica base'),
        ),
    ]
