# Generated by Django 6.0.3 on 2026-04-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_configurazione_sms_url_pubblica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurazionesistema',
            name='url_pubblica_base',
            field=models.CharField(blank=True, default='', help_text='Solo scheme + host, senza path e senza slash finale (es. https://www.plazapretoria.it oppure https://gesper.plazapretoria.it). Il prefisso applicazione (es. /gesper/) lo aggiunge sempre Django con reverse(). Usata per link in e-mail/SMS quando la richiesta arriva da host di sviluppo (localhost, [::1], *.local, …).', max_length=300, verbose_name='URL pubblica base'),
        ),
    ]
