# Generated by Django 6.0.3 on 2026-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_email_stepup_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurazionesistema',
            name='url_pubblica_base',
            field=models.CharField(blank=True, default='', help_text='Solo scheme + host, senza path e senza slash finale (es. https://www.plazapretoria.it oppure https://gesper.plazapretoria.it). Il prefisso applicazione (es. /gesper/) lo aggiunge sempre Django con reverse(). Usata per link in e-mail quando la richiesta arriva da host di sviluppo (localhost, [::1], *.local, …).', max_length=300, verbose_name='URL pubblica base'),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='Se attivo, dopo la password serve il codice dall’app authenticator (stesso flusso API e login web).', verbose_name='2FA app (TOTP)'),
        ),
    ]
