# Generated by Django 6.0.3 on 2026-04-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_force_disable_sms_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionesistema',
            name='firmatario_amministratore_nome',
            field=models.CharField(blank=True, default='', help_text='Nome e cognome del titolare/legale rappresentante da usare nei documenti firmati.', max_length=150, verbose_name='Nome firmatario amministratore'),
        ),
        migrations.AddField(
            model_name='configurazionesistema',
            name='firmatario_amministratore_ruolo',
            field=models.CharField(blank=True, default='', help_text='Es. Amministratore unico, Legale rappresentante.', max_length=150, verbose_name='Ruolo firmatario amministratore'),
        ),
    ]
