# Generated by Django 6.0.3 on 2026-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_configurazionesistema_firmatario_amministratore_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilocandidato',
            name='cap',
            field=models.CharField(blank=True, max_length=10, verbose_name='CAP'),
        ),
    ]
