# Generated by Django 6.0.3 on 2026-04-29 19:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_configurazionesistema_simulatore_paga_riepilogo_cedolino_canonico'),
        ('anagrafiche', '0013_azienda_sede_legale_strutturata_amministratore'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoRegistroStudioConsulente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('proforma', 'Proforma'), ('parcella', 'Parcella'), ('sconosciuto', 'Non classificato')], default='sconosciuto', max_length=20, verbose_name='Tipo')),
                ('numero_documento', models.CharField(blank=True, default='', max_length=80, verbose_name='Numero documento')),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='Data documento')),
                ('totale_da_pagare', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Totale da pagare (letto)')),
                ('dare', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Dare')),
                ('avere', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Avere')),
                ('saldo_progressivo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Saldo progressivo')),
                ('nome_file', models.CharField(max_length=280, verbose_name='Nome file origine')),
                ('file', models.FileField(blank=True, null=True, upload_to='registro_studio_consulente/%Y/%m/', verbose_name='PDF archiviato')),
                ('testo_estratto', models.TextField(blank=True, default='', verbose_name='Testo estratto / OCR')),
                ('metodo_estrazione', models.CharField(blank=True, default='', max_length=20, verbose_name='Metodo estrazione')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='Note / avvisi import')),
                ('importato_il', models.DateTimeField(auto_now_add=True, verbose_name='Importato il')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti_registro_studio', to='anagrafiche.azienda', verbose_name='Azienda')),
                ('importato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_registro_studio', to=settings.AUTH_USER_MODEL, verbose_name='Importato da')),
            ],
            options={
                'verbose_name': 'Movimento registro studio (proforma/parcella)',
                'verbose_name_plural': 'Movimenti registro studio (proforma/parcele)',
                'ordering': ['data_documento', 'importato_il', 'id'],
                'indexes': [models.Index(fields=['azienda', 'data_documento'], name='accounts_mo_azienda_0b4a41_idx'), models.Index(fields=['azienda', '-importato_il'], name='accounts_mo_azienda_3a4c05_idx')],
                'constraints': [models.UniqueConstraint(fields=('azienda', 'nome_file'), name='uniq_regstudio_azienda_nomefile')],
            },
        ),
    ]
