#!/usr/bin/env bash
# Comandi di riferimento post-deploy (eseguire sul server, percorsi da adattare).
# Procedura completa DNS + Nginx + Certbot + PWA: deploy/PROCEDURA_DEPLOY.md
set -euo pipefail
cd "$(dirname "$0")/.."

export DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE:-settings_production}"

echo "== migrate =="
./.venv/bin/python manage.py migrate --noinput

echo "== collectstatic =="
./.venv/bin/python manage.py collectstatic --noinput

echo "OK. Riavviare Gunicorn e ricaricare Nginx:"
echo "  Modalità consigliata (solo gesper.* sulla VPS):"
echo "    sudo systemctl restart gesper"
echo "  Opzionale — split www sulla VPS con path /gesper/ su www:"
echo "    sudo systemctl restart gesper gesper-www"
echo "  sudo nginx -t && sudo systemctl reload nginx"
echo "  (Gunicorn: --timeout 900 per «Ricarica libro paga» / PDF lunghi; Nginx: proxy_read_timeout 900s.)"
echo "  Fix HTTP 400 (DisallowedHost): settings_production USE_X_FORWARDED_HOST=False + Nginx proxy_set_header X-Forwarded-Host \$host;"
echo ""
echo "Stack produzione (default): gesper (8000, root su gesper1.plazapretoria.it)."
echo "Nginx: deploy/nginx-gesper-vps-standalone.conf"
echo "gesper-www (8003) + settings_production_www servono solo con deploy/nginx-gesper-production-split.conf;"
echo "  in solo sottodominio: sudo systemctl disable --now gesper-www"
echo ""
echo "Archivio documenti (sottocartelle MEDIA vs tipi in DB):"
echo "  All'avvio Django crea le cartelle (documenti/upload_paths.ensure_documenti_media_subdirs)."
echo "  Dry-run riallineamento path file → cartelle per tipo:"
echo "    ./.venv/bin/python manage.py normalizza_archivio_documenti"
echo "  Applica spostamento file + aggiornamento record:"
echo "    ./.venv/bin/python manage.py normalizza_archivio_documenti --applica"
echo "  Inventario/orfani buste (opzionale):"
echo "    ./.venv/bin/python manage.py inventario_archivio_payroll --list-orphans --max-list=200"
echo ""
echo "TLS (Let's Encrypt / Certbot):"
echo "  Sul server LIVE i blocchi HTTPS 443 sono gestiti da Certbot (es. certbot --nginx -d gesper1.plazapretoria.it)."
echo "  Non modificare a mano ssl_certificate / ssl_certificate_key; non duplicare server 443."
echo "  Preservare sempre listen 80 + location /.well-known/acme-challenge/ per il rinnovo."
echo "  Test rinnovo: sudo certbot renew --dry-run"
echo "  Poi: sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "Radice dati (DB + media + archivio/):"
echo "  Produzione: GESPER_DATA_ROOT=/var/www/documento in EnvironmentFile (vedi PROCEDURA_DEPLOY.md)."
echo "  Nginx alias /media/ → stessa radice …/documento/media/"
echo ""
echo "DNS (pannello Hosting Linux / domini Aruba — vedi deploy/PROCEDURA_DEPLOY.md):"
echo "  Modalità separata: A gesper1 (o gesper) → IPv4 VPS; www / @ → hosting WordPress (non la VPS)."
echo "  Split (opzionale): A www → VPS; upstream WordPress in nginx-gesper-production-split.conf."
echo "  Non usare IP del router domestico."
echo "  Verifica: dig +short gesper1.plazapretoria.it A"
echo ""
echo "PWA + static in un colpo (da Mac con SSH): deploy/sync-pwa-and-collectstatic.sh"
echo "  Solo PWA: deploy/sync-gesper-app.example.sh (GESPER_DEPLOY_HOST, GESPER_REMOTE_APP_DIR, …)."
echo ""
echo "Verifica pubblica (curl, senza SSH): ./deploy/verify-public-endpoints.sh"
echo "Backup Nginx sul server prima di edit: sudo bash deploy/backup-nginx-site.sh"
