# Generated by Django 6.0.3 on 2026-03-05 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contratto', 'Contratto di lavoro'), ('privacy', 'Autorizzazione privacy'), ('busta_paga', 'Busta paga'), ('certificato', 'Certificato'), ('altro', 'Altro')], max_length=30, verbose_name='Tipo documento')),
                ('file', models.FileField(upload_to='documenti/', verbose_name='File')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True, verbose_name='Data caricamento')),
                ('visibile_al_dipendente', models.BooleanField(default=True, verbose_name='Visibile al dipendente')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.azienda', verbose_name='Azienda')),
                ('caricato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anagrafiche.user', verbose_name='Caricato da')),
                ('dipendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.dipendente', verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
            },
        ),
    ]
