# Generated by Django 6.0.3 on 2026-04-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0010_cedolinomotorev4_scatti_superminimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedolinomotorev4',
            name='verifica_n_checks_formula_ko_bloccanti',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Conteggi F3–F5, F8, F9 che determinano OK/differenze; esclusi F1, F2, F7 diagnostici.', null=True, verbose_name='N° formule KO bloccanti (esito badge)'),
        ),
        migrations.AlterField(
            model_name='cedolinomotorev4',
            name='verifica_n_checks_formula_ko',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='N° formule KO (tutte F1–F9)'),
        ),
    ]
