# Generated by Django 6.0.3 on 2026-04-12 15:57

import documenti.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0011_cedolino_verifica_n_checks_bloccanti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(upload_to=documenti.upload_paths.documento_file_upload_to, verbose_name='File'),
        ),
    ]
