# Generated by Django 6.0.3 on 2026-04-12 17:56

from collections import defaultdict

from django.db import migrations, models


def _natura_calcolata(row) -> str:
    tc = (getattr(row, "tipo_cedolino", None) or "").upper()
    fp = (getattr(row, "file_pdf", None) or "").upper()
    if "QUATTORDICESIMA" in tc or "QUATTORDICESIMA" in fp:
        return "QUATTORDICESIMA"
    if "TREDICESIMA" in tc or "TREDICESIMA" in fp:
        return "TREDICESIMA"
    return "ORDINARIA"


def _elimina_cedolini_duplicati(apps, pks: list[int], using: str) -> None:
    """
    Rimuove righe ``CedolinoMotoreV4`` senza affidarsi al collector CASCADE sui modelli storici
    (SQLite: altrimenti FOREIGN KEY su voci/validazioni).
    """
    if not pks:
        return
    Voce = apps.get_model("documenti", "VoceCedolinoMotoreV4")
    Val = apps.get_model("documenti", "ValidazioneCedolinoMotoreV4")
    CedolinoMotoreV4 = apps.get_model("documenti", "CedolinoMotoreV4")
    Voce.objects.using(using).filter(cedolino_id__in=pks).delete()
    Val.objects.using(using).filter(cedolino_id__in=pks).delete()
    CedolinoMotoreV4.objects.using(using).filter(pk__in=pks).delete()


def _natura_da_tipo_e_file(apps, schema_editor):
    """
    Imposta ``natura_busta`` da tipo/file evitando violazioni del nuovo vincolo univoco
    (dipendente, mese, anno, natura_busta): elimina duplicati storici e aggiorna le righe residue.
    """
    using = schema_editor.connection.alias
    CedolinoMotoreV4 = apps.get_model("documenti", "CedolinoMotoreV4")

    # 1) Stessa quadrupla (dipendente, mese, anno, natura calcolata): conserva il pk più basso.
    quad: dict[tuple[int, int, int, str], list[int]] = defaultdict(list)
    for row in CedolinoMotoreV4.objects.using(using).all().order_by("pk").iterator():
        quad[(row.dipendente_id, row.mese, row.anno, _natura_calcolata(row))].append(row.pk)
    del_quad = [pk for pks in quad.values() for pk in sorted(pks)[1:]]
    if del_quad:
        _elimina_cedolini_duplicati(apps, del_quad, using)

    # 2) Stesso (dipendente, mese, anno): al più una riga per natura (max 3); elimina le successive.
    trip: dict[tuple[int, int, int], list[tuple[int, str]]] = defaultdict(list)
    for row in CedolinoMotoreV4.objects.using(using).all().order_by("pk").iterator():
        trip[(row.dipendente_id, row.mese, row.anno)].append((row.pk, _natura_calcolata(row)))
    del_trip: list[int] = []
    for pairs in trip.values():
        seen_n: set[str] = set()
        for pk, nat in pairs:
            if nat in seen_n:
                del_trip.append(pk)
            elif len(seen_n) >= 3:
                del_trip.append(pk)
            else:
                seen_n.add(nat)
    if del_trip:
        _elimina_cedolini_duplicati(apps, del_trip, using)

    # 3) Aggiorna il campo sui record superstiti.
    for row in CedolinoMotoreV4.objects.using(using).all().iterator():
        natura = _natura_calcolata(row)
        if row.natura_busta != natura:
            row.natura_busta = natura
            row.save(using=using, update_fields=["natura_busta"])


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0008_dipendente_matricola'),
        ('documenti', '0012_documento_upload_to_buste_pagne'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cedolinomotorev4',
            name='uniq_cedolino_motore_v4_dip_mese_anno',
        ),
        migrations.RemoveIndex(
            model_name='cedolinomotorev4',
            name='documenti_c_dipende_2bdae4_idx',
        ),
        migrations.AddField(
            model_name='cedolinomotorev4',
            name='natura_busta',
            field=models.CharField(choices=[('ORDINARIA', 'Ordinaria'), ('TREDICESIMA', 'Tredicesima'), ('QUATTORDICESIMA', 'Quattordicesima')], default='ORDINARIA', help_text='Distinzione 13ª/14ª vs ordinario quando il periodo retributivo coincide (es. dicembre).', max_length=20, verbose_name='Natura busta'),
        ),
        migrations.RunPython(_natura_da_tipo_e_file, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='cedolinomotorev4',
            index=models.Index(fields=['dipendente', 'anno', 'mese', 'natura_busta'], name='documenti_c_dipende_87f18d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cedolinomotorev4',
            constraint=models.UniqueConstraint(fields=('dipendente', 'mese', 'anno', 'natura_busta'), name='uniq_cedolino_motore_v4_dip_mese_anno_natura'),
        ),
    ]
