# Generated by Django 6.0.3 on 2026-04-12 17:56

from django.db import migrations, models


def _natura_da_tipo_e_file(apps, schema_editor):
    CedolinoMotoreV4 = apps.get_model("documenti", "CedolinoMotoreV4")
    for row in CedolinoMotoreV4.objects.all().iterator():
        tc = (getattr(row, "tipo_cedolino", None) or "").upper()
        fp = (getattr(row, "file_pdf", None) or "").upper()
        natura = "ORDINARIA"
        if "QUATTORDICESIMA" in tc or "QUATTORDICESIMA" in fp:
            natura = "QUATTORDICESIMA"
        elif "TREDICESIMA" in tc or "TREDICESIMA" in fp:
            natura = "TREDICESIMA"
        if row.natura_busta != natura:
            row.natura_busta = natura
            row.save(update_fields=["natura_busta"])


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0008_dipendente_matricola'),
        ('documenti', '0012_documento_upload_to_buste_pagne'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cedolinomotorev4',
            name='uniq_cedolino_motore_v4_dip_mese_anno',
        ),
        migrations.RemoveIndex(
            model_name='cedolinomotorev4',
            name='documenti_c_dipende_2bdae4_idx',
        ),
        migrations.AddField(
            model_name='cedolinomotorev4',
            name='natura_busta',
            field=models.CharField(choices=[('ORDINARIA', 'Ordinaria'), ('TREDICESIMA', 'Tredicesima'), ('QUATTORDICESIMA', 'Quattordicesima')], default='ORDINARIA', help_text='Distinzione 13ª/14ª vs ordinario quando il periodo retributivo coincide (es. dicembre).', max_length=20, verbose_name='Natura busta'),
        ),
        migrations.RunPython(_natura_da_tipo_e_file, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='cedolinomotorev4',
            index=models.Index(fields=['dipendente', 'anno', 'mese', 'natura_busta'], name='documenti_c_dipende_87f18d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cedolinomotorev4',
            constraint=models.UniqueConstraint(fields=('dipendente', 'mese', 'anno', 'natura_busta'), name='uniq_cedolino_motore_v4_dip_mese_anno_natura'),
        ),
    ]
