# Generated by Django 6.0.3 on 2026-03-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0004_dipendente_candidato_fields'),
        # Rimuove anagrafiche.User solo dopo che i FK sono stati spostati su AUTH_USER_MODEL
        ('documenti', '0002_alter_documento_caricato_da'),
        ('presenze', '0002_alter_presenza_registrata_da'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
