# Generated by Django 6.0.3 on 2026-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='sede_lavorativa_indirizzo',
            field=models.CharField(blank=True, help_text='Indirizzo operativo dove avviene la timbratura (può differire dalla sede sociale).', max_length=255, verbose_name='Indirizzo sede lavorativa'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='sede_lavorativa_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Formato decimale, es. 38.117940', max_digits=9, null=True, verbose_name='Latitudine sede lavorativa'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='sede_lavorativa_lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Formato decimale, es. 13.362860', max_digits=9, null=True, verbose_name='Longitudine sede lavorativa'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='sede_lavorativa_raggio_m',
            field=models.PositiveIntegerField(default=180, help_text='Raggio massimo consentito per timbratura valida.', verbose_name='Raggio geofence sede (metri)'),
        ),
    ]
