# Generated by Django 6.0.3 on 2026-04-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0006_azienda_sede_lavorativa_indirizzo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='mansione',
            field=models.CharField(blank=True, choices=[('', '— Non specificata —'), ('cuoco', 'Cuoco/a'), ('piazzista', 'Piazziolo/a'), ('cameriere', 'Cameriere/a'), ('fattorino', 'Fattorino/a'), ('amministrativo', 'Amministrativo')], default='', help_text='Qualifica operativa / reparto (lista standard).', max_length=32, verbose_name='Mansione'),
        ),
    ]
