# Generated by Django 6.0.3 on 2026-04-09 17:18

from django.conf import settings
from django.db import migrations, models
from django.db.models import Max


def backfill_matricole(apps, schema_editor):
    Dip = apps.get_model('anagrafiche', 'Dipendente')
    for row in Dip.objects.values('azienda_id').distinct():
        aid = row['azienda_id']
        if aid is None:
            continue
        max_m = Dip.objects.filter(azienda_id=aid).exclude(matricola__isnull=True).aggregate(
            m=Max('matricola')
        )['m']
        nxt = max_m or 0
        for d in Dip.objects.filter(azienda_id=aid, matricola__isnull=True).order_by('pk'):
            nxt += 1
            Dip.objects.filter(pk=d.pk).update(matricola=nxt)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0007_dipendente_mansione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='matricola',
            field=models.PositiveIntegerField(blank=True, help_text='Numero univoco per azienda. Vuoto in creazione = assegnazione automatica.', null=True, verbose_name='Matricola'),
        ),
        migrations.RunPython(backfill_matricole, noop_reverse),
        migrations.AddConstraint(
            model_name='dipendente',
            constraint=models.UniqueConstraint(condition=models.Q(('matricola__isnull', False)), fields=('azienda', 'matricola'), name='uniq_dip_matricola_per_azienda'),
        ),
    ]
