# Generated by Django 6.0.3 on 2026-04-27 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0008_dipendente_matricola'),
        ('documenti', '0014_alter_documento_tipo_unilav_riepilogo'),
        ('rapporto_di_lavoro', '0042_alter_simulazioneorganico_mese_riferimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicazioneRecessoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('in_verifica_consulente', 'In verifica consulente'), ('verificata_consulente', 'Verificata consulente'), ('firmata_admin', 'Firmata amministratore'), ('inviata_dipendente', 'Inviata al dipendente')], default='bozza', max_length=40)),
                ('testo_bozza', models.TextField(blank=True, default='')),
                ('note_consulente', models.TextField(blank=True, default='')),
                ('data_verifica_consulente', models.DateTimeField(blank=True, null=True)),
                ('firmatario_nome', models.CharField(blank=True, default='', max_length=150)),
                ('firmatario_ruolo', models.CharField(blank=True, default='', max_length=150)),
                ('data_firma_admin', models.DateTimeField(blank=True, null=True)),
                ('inviata_email', models.BooleanField(default=False)),
                ('data_invio_email', models.DateTimeField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicazioni_recesso_prova', to='anagrafiche.azienda')),
                ('consulente_verificatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recessi_prova_verificati', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recessi_prova_creati', to=settings.AUTH_USER_MODEL)),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicazioni_recesso_prova', to='anagrafiche.dipendente')),
                ('documento_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicazioni_recesso_prova_pdf', to='documenti.documento')),
                ('firmato_da_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recessi_prova_firmati', to=settings.AUTH_USER_MODEL)),
                ('modificato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recessi_prova_modificati', to=settings.AUTH_USER_MODEL)),
                ('rapporto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicazioni_recesso_prova', to='rapporto_di_lavoro.rapportodilavoro')),
            ],
            options={
                'verbose_name': 'Comunicazione recesso periodo prova',
                'verbose_name_plural': 'Comunicazioni recesso periodo prova',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
