# Generated by Django 6.0.3 on 2026-04-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0009_comunicazionerecessoprova'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='cap',
            field=models.CharField(blank=True, max_length=10, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='citta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Citta'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='luogo_nascita',
            field=models.CharField(blank=True, max_length=100, verbose_name='Luogo di nascita'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='provincia',
            field=models.CharField(blank=True, max_length=2, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='sesso',
            field=models.CharField(blank=True, choices=[('', '— Non specificato —'), ('M', 'Maschile'), ('F', 'Femminile'), ('A', 'Preferisco non specificare')], default='', max_length=1, verbose_name='Sesso'),
        ),
    ]
