# Generated by Django 6.0.3 on 2026-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0010_dipendente_cap_dipendente_citta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='comune_nascita',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comune di nascita'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='domicilio_cap',
            field=models.CharField(blank=True, max_length=10, verbose_name='Domicilio - CAP'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='domicilio_comune',
            field=models.CharField(blank=True, max_length=100, verbose_name='Domicilio - Comune'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='domicilio_indirizzo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domicilio - indirizzo'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='domicilio_provincia',
            field=models.CharField(blank=True, max_length=2, verbose_name='Domicilio - Provincia'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='domicilio_regione',
            field=models.CharField(blank=True, max_length=100, verbose_name='Domicilio - Regione'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='domicilio_uguale_residenza',
            field=models.BooleanField(default=True, verbose_name='Domicilio uguale a residenza'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='provincia_nascita',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia di nascita'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='regione_nascita',
            field=models.CharField(blank=True, max_length=100, verbose_name='Regione di nascita'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='regione_residenza',
            field=models.CharField(blank=True, max_length=100, verbose_name='Regione di residenza'),
        ),
    ]
