# Generated by Django 6.0.3 on 2026-04-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0011_dipendente_comune_nascita_dipendente_domicilio_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='cittadinanza',
            field=models.CharField(blank=True, default='ITALIANA', max_length=100, verbose_name='Cittadinanza'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='paese_domicilio',
            field=models.CharField(blank=True, default='ITALIA', max_length=100, verbose_name='Domicilio - Paese'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='paese_nascita',
            field=models.CharField(blank=True, default='ITALIA', max_length=100, verbose_name='Paese di nascita'),
        ),
        migrations.AddField(
            model_name='dipendente',
            name='paese_residenza',
            field=models.CharField(blank=True, default='ITALIA', max_length=100, verbose_name='Paese di residenza'),
        ),
    ]
