# Generated by Django 6.0.3

from django.db import migrations, models


def forwards_copy_indirizzo(apps, schema_editor):
    Azienda = apps.get_model('anagrafiche', 'Azienda')
    for row in Azienda.objects.all():
        via = (getattr(row, 'sede_legale_via', None) or '').strip()
        if not via and (row.indirizzo or '').strip():
            row.sede_legale_via = (row.indirizzo or '')[:255]
            row.save(update_fields=['sede_legale_via'])


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0012_dipendente_cittadinanza_dipendente_paese_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='sede_legale_regione',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Regione (sede legale)'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='sede_legale_provincia',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Provincia (sigla, sede legale)'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='sede_legale_comune',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Comune (sede legale)'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='sede_legale_cap',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CAP (sede legale)'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='sede_legale_via',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Es. Via Roma 12 — da affiancare a comune e CAP.',
                max_length=255,
                verbose_name='Via e numero civico (sede legale)',
            ),
        ),
        migrations.AddField(
            model_name='azienda',
            name='amministratore_pro_tempore_nome',
            field=models.CharField(
                blank=True,
                default='',
                max_length=200,
                verbose_name='Amministratore pro tempore (nome e cognome)',
            ),
        ),
        migrations.AddField(
            model_name='azienda',
            name='amministratore_pro_tempore_ruolo',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Es. Amministratore delegato, Legale rappresentante.',
                max_length=150,
                verbose_name='Amministratore pro tempore (ruolo)',
            ),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='indirizzo',
            field=models.CharField(
                help_text='Compilato automaticamente da via, CAP e comune; usato nei report che richiedono una sola riga.',
                max_length=255,
                verbose_name='Indirizzo sede legale (riepilogo)',
            ),
        ),
        migrations.RunPython(forwards_copy_indirizzo, migrations.RunPython.noop),
    ]
