# Generated by Django 6.0.3 on 2026-03-05 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ferie', 'Ferie'), ('permesso', 'Permesso'), ('malattia', 'Malattia'), ('altro', 'Altro')], max_length=20)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('stato', models.CharField(choices=[('inviata', 'Inviata'), ('approvata', 'Approvata'), ('rifiutata', 'Rifiutata')], default='inviata', max_length=20)),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('data_risposta', models.DateTimeField(blank=True, null=True)),
                ('note_risposta', models.CharField(blank=True, max_length=255)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.azienda')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste', to='anagrafiche.dipendente')),
                ('richiesta_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('risposta_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risposte_richieste', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_richiesta'],
            },
        ),
    ]
