# Generated by Django 6.0.3 on 2026-03-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richieste', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='richiesta',
            options={'ordering': ['-data_richiesta'], 'verbose_name': 'Richiesta', 'verbose_name_plural': 'Richieste'},
        ),
        migrations.AddField(
            model_name='richiesta',
            name='testo_richiesta',
            field=models.TextField(blank=True, verbose_name='Testo richiesta'),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='data_fine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='data_inizio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='note_risposta',
            field=models.TextField(blank=True, verbose_name='Risposta / Note'),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='stato',
            field=models.CharField(choices=[('inviata', 'Inviata'), ('approvata', 'Approvata'), ('rifiutata', 'Rifiutata'), ('chiusa', 'Chiusa')], default='inviata', max_length=20),
        ),
        migrations.AlterField(
            model_name='richiesta',
            name='tipo',
            field=models.CharField(choices=[('ferie', 'Ferie'), ('permesso', 'Permesso'), ('malattia', 'Malattia'), ('generica', 'Richiesta generica / Chiarimento'), ('altro', 'Altro')], max_length=20),
        ),
    ]
