# Generated by Django 6.0.3 on 2026-04-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoceGuida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_modulo', models.SlugField(help_text='Es. reg-dipendente (vedi guida/registry.py).', max_length=64, verbose_name='Codice modulo')),
                ('codice_campo', models.SlugField(blank=True, help_text='Vuoto = testo introduttivo del modulo; altrimenti chiave campo/form.', max_length=64, verbose_name='Codice campo')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('testo', models.TextField(help_text='Testo esplicativo. Righe vuote = paragrafi in visualizzazione.', verbose_name='Testo')),
                ('attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('ordine', models.PositiveSmallIntegerField(default=0, help_text='Ordine di visualizzazione nella pagina modulo (0 = primo).', verbose_name='Ordine')),
                ('aggiornata_il', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
            ],
            options={
                'verbose_name': 'Voce guida',
                'verbose_name_plural': 'Voci guida',
                'ordering': ['codice_modulo', 'ordine', 'codice_campo', 'titolo'],
                'indexes': [models.Index(fields=['codice_modulo', 'attiva'], name='guida_voceg_codice__808faf_idx')],
                'constraints': [models.UniqueConstraint(fields=('codice_modulo', 'codice_campo'), name='guida_voce_unica_modulo_campo')],
            },
        ),
    ]
