# Generated by Django 6.0.3 on 2026-05-10 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0013_azienda_sede_legale_strutturata_amministratore'),
        ('documenti', '0015_documento_tipo_ricevuta_pagamento_netto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoPartitarioNettoDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('busta_netto', 'Netto da busta paga (DARE)'), ('pagamento', 'Pagamento al dipendente (AVERE)')], max_length=20, verbose_name='Tipo movimento')),
                ('lato', models.CharField(choices=[('DARE', 'Dare'), ('AVERE', 'Avere')], max_length=5, verbose_name='Dare / Avere')),
                ('anno', models.PositiveSmallIntegerField(verbose_name='Anno di competenza')),
                ('mese', models.PositiveSmallIntegerField(verbose_name='Mese (1–12)')),
                ('data_contabile', models.DateField(help_text="Ultimo giorno del mese per il netto busta; data effettiva del pagamento per l'AVERE.", verbose_name='Data contabile')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Importo (€)')),
                ('natura_busta', models.CharField(default='ORDINARIA', help_text='Ordinaria / tredicesima / quattordicesima; per i pagamenti resta «ordinaria» se non diversamente indicato.', max_length=20, verbose_name='Natura busta (riferimento)')),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('contanti', 'Contanti'), ('bonifico', 'Bonifico bancario')], default='', max_length=20, verbose_name='Modalità pagamento')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('aggiornato_il', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti_partitario_netto', to='anagrafiche.azienda', verbose_name='Azienda')),
                ('cedolino_motore_v4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_partitario_netto', to='documenti.cedolinomotorev4', verbose_name='Cedolino motore v4')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti_partitario_netto', to='anagrafiche.dipendente', verbose_name='Dipendente')),
                ('documento_busta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_partitario_da_busta', to='documenti.documento', verbose_name='Documento busta collegato')),
                ('documento_ricevuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_partitario_ricevuta', to='documenti.documento', verbose_name='Allegato ricevuta / bonifico')),
                ('inserito_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_partitario_netto_inseriti', to=settings.AUTH_USER_MODEL, verbose_name='Inserito da')),
            ],
            options={
                'verbose_name': 'Movimento partitario netto dipendente',
                'verbose_name_plural': 'Movimenti partitario netti dipendenti',
                'ordering': ('-anno', '-mese', 'dipendente__cognome', 'dipendente__nome', '-data_contabile', '-id'),
                'indexes': [models.Index(fields=['azienda', 'anno', 'mese'], name='partitario__azienda_4c6f01_idx'), models.Index(fields=['azienda', 'dipendente', 'anno', 'mese'], name='partitario__azienda_fe2285_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo_movimento', 'busta_netto')), fields=('azienda', 'dipendente', 'anno', 'mese', 'natura_busta'), name='uniq_partitario_netto_busta_periodo')],
            },
        ),
    ]
