# Generated by Django 6.0.3 on 2026-03-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('richieste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_richiesta', models.CharField(choices=[('ferie', 'Ferie'), ('permesso', 'Permesso'), ('malattia', 'Malattia')], max_length=50)),
                ('numero_step', models.IntegerField(default=1)),
                ('richiede_documenti', models.BooleanField(default=False)),
                ('timeout_giorni', models.IntegerField(default=3)),
                ('notifica_rifiuto', models.BooleanField(default=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workflow Richiesta',
                'verbose_name_plural': 'Workflow Richieste',
                'unique_together': {('tipo_richiesta', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='StepApprovazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_step', models.IntegerField()),
                ('titolo', models.CharField(max_length=100)),
                ('ruolo_approvatore', models.CharField(choices=[('manager', 'Manager diretto'), ('hr', 'HR'), ('admin', 'Administrator')], max_length=50)),
                ('puo_approvare', models.BooleanField(default=True)),
                ('puo_rifiutare', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.richiestaworkflow')),
            ],
            options={
                'verbose_name': 'Step Approvazione',
                'verbose_name_plural': 'Step Approvazioni',
                'ordering': ['workflow', 'numero_step'],
                'unique_together': {('workflow', 'numero_step')},
            },
        ),
        migrations.CreateModel(
            name='RichiestaApprovazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('approvato', 'Approvato'), ('rifiutato', 'Rifiutato')], default='in_attesa', max_length=20)),
                ('data_assegnazione', models.DateTimeField(auto_now_add=True)),
                ('data_azione', models.DateTimeField(blank=True, null=True)),
                ('commento', models.TextField(blank=True)),
                ('notifica_inviata', models.BooleanField(default=False)),
                ('approvatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='da_approvare', to=settings.AUTH_USER_MODEL)),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvazioni_workflow', to='richieste.richiesta')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.stepapprovazione')),
            ],
            options={
                'verbose_name': 'Richiesta Approvazione',
                'verbose_name_plural': 'Richieste Approvazione',
                'ordering': ['data_assegnazione'],
            },
        ),
    ]
