# Generated by Django 6.0.3 on 2026-03-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContratto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ccnl', models.CharField(max_length=100)),
                ('durata_giorni', models.IntegerField(blank=True, null=True)),
                ('prova_giorni', models.IntegerField(default=30)),
                ('prorogabile', models.BooleanField(default=True)),
                ('rinnovabile', models.BooleanField(default=False)),
                ('descrizione', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo Contratto',
                'verbose_name_plural': 'Tipi Contratto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RapportoDiLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contratto', models.CharField(max_length=50, unique=True)),
                ('data_sottoscrizione', models.DateField(blank=True, null=True)),
                ('data_inizio_rapporto', models.DateField()),
                ('data_fine_rapporto', models.DateField(blank=True, null=True)),
                ('posizione', models.CharField(max_length=100)),
                ('livello_ccnl', models.CharField(max_length=50)),
                ('qualifica', models.CharField(max_length=100)),
                ('stipendio_lordo_mensile', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tredicesima', models.BooleanField(default=True)),
                ('quattordicesima', models.BooleanField(default=False)),
                ('premio_obiettivi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ore_settimanali', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('turno_tipo', models.CharField(choices=[('diurno', 'Diurno'), ('notturno', 'Notturno'), ('turnista', 'Turnista'), ('flessibile', 'Flessibile')], default='diurno', max_length=50)),
                ('giorni_ferie_annuali', models.IntegerField(default=20)),
                ('giorni_permesso_annuali', models.IntegerField(default=3)),
                ('giorni_malattia_retribuiti', models.IntegerField(default=0)),
                ('aliquota_tfr', models.DecimalField(decimal_places=2, default=6.5, max_digits=5)),
                ('fondo_pensione', models.CharField(blank=True, max_length=100, null=True)),
                ('file_contratto_pdf', models.FileField(blank=True, null=True, upload_to='contratti/pdf/')),
                ('file_proposta', models.FileField(blank=True, null=True, upload_to='contratti/proposte/')),
                ('stato', models.CharField(choices=[('proposta', 'Proposta'), ('sottoscritto', 'Sottoscritto'), ('sospeso', 'Sospeso'), ('cessato', 'Cessato')], default='proposta', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapporti_di_lavoro', to='anagrafiche.azienda')),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapporti_creati', to=settings.AUTH_USER_MODEL)),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapporti_di_lavoro', to='anagrafiche.dipendente')),
                ('modificato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapporti_modificati', to=settings.AUTH_USER_MODEL)),
                ('tipo_contratto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rapporto_di_lavoro.tipocontratto')),
            ],
            options={
                'verbose_name': 'Rapporto di Lavoro',
                'verbose_name_plural': 'Rapporti di Lavoro',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='VariazioneContratto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_variazione', models.DateField()),
                ('tipo', models.CharField(choices=[('livello', 'Cambio Livello'), ('stipendio', 'Aumento Stipendio'), ('ore', 'Variazione Orario'), ('qualifica', 'Cambio Qualifica'), ('altro', 'Altro')], max_length=50)),
                ('campo_modificato', models.CharField(max_length=100)),
                ('valore_precedente', models.TextField()),
                ('valore_nuovo', models.TextField()),
                ('motivo', models.TextField()),
                ('file_documentazione', models.FileField(blank=True, null=True, upload_to='variazioni/')),
                ('data_registrazione', models.DateTimeField(auto_now_add=True)),
                ('rapporto_di_lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variazioni', to='rapporto_di_lavoro.rapportodilavoro')),
                ('registrata_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variazione Contratto',
                'verbose_name_plural': 'Variazioni Contratto',
                'ordering': ['-data_variazione'],
            },
        ),
    ]
