# Generated by Django 6.0.3 on 2026-03-07 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0002_alter_dipendente_utente'),
        ('rapporto_di_lavoro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloContrattuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('categoria', models.CharField(choices=[('proposta_assunzione', 'Proposta assunzione'), ('integrazione_dati', 'Integrazione dati dipendente'), ('consenso_privacy', 'Consenso privacy'), ('allegati_obbligatori', 'Allegati obbligatori'), ('altro', 'Altro')], default='proposta_assunzione', max_length=50)),
                ('descrizione', models.TextField(blank=True)),
                ('compilabile_da_dipendente', models.BooleanField(default=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modulo Contrattuale',
                'verbose_name_plural': 'Moduli Contrattuali',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ParametroCCNLTurismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccnl', models.CharField(default='Turismo Confcommercio', max_length=150)),
                ('versione', models.CharField(default='2024-2026', max_length=50)),
                ('sezione', models.CharField(choices=[('ristoranti_pizzerie', 'Ristoranti/Pizzerie con cucina'), ('somministrazione_tavoli', 'Somministrazione e servizio ai tavoli')], default='ristoranti_pizzerie', max_length=50)),
                ('livello', models.CharField(max_length=20)),
                ('qualifica', models.CharField(max_length=120)),
                ('tipo_contratto_nazionale', models.CharField(max_length=120)),
                ('importo_lordo_mensile', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indennita_mensile', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ore_settimanali', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('ore_mensili', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ore_giornaliere', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parametro CCNL Turismo',
                'verbose_name_plural': 'Parametri CCNL Turismo',
                'ordering': ['sezione', 'livello', 'qualifica'],
                'unique_together': {('ccnl', 'versione', 'sezione', 'livello', 'qualifica')},
            },
        ),
        migrations.CreateModel(
            name='PropostaAssunzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proposta', models.CharField(max_length=50, unique=True)),
                ('titolo', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True)),
                ('data_inizio_rapporto', models.DateField()),
                ('data_fine_rapporto', models.DateField(blank=True, null=True)),
                ('posizione', models.CharField(max_length=100)),
                ('livello_ccnl', models.CharField(max_length=50)),
                ('qualifica', models.CharField(max_length=100)),
                ('stipendio_lordo_mensile', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indennita_mensile', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ore_settimanali', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('ore_mensili', models.DecimalField(decimal_places=2, default=173.33, max_digits=6)),
                ('ore_giornaliere', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('accettata_dipendente', models.BooleanField(default=False)),
                ('data_accettazione_dipendente', models.DateTimeField(blank=True, null=True)),
                ('note_dipendente', models.TextField(blank=True)),
                ('approvata_admin', models.BooleanField(default=False)),
                ('data_approvazione_admin', models.DateTimeField(blank=True, null=True)),
                ('note_admin', models.TextField(blank=True)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('inviata_al_dipendente', 'Inviata al dipendente'), ('accettata_dipendente', 'Accettata dal dipendente'), ('rifiutata_dipendente', 'Rifiutata dal dipendente'), ('in_revisione_admin', 'In revisione admin'), ('approvata_admin', 'Approvata admin'), ('rifiutata_admin', 'Rifiutata admin'), ('convertita_in_contratto', 'Convertita in contratto')], default='bozza', max_length=30)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte_assunzione', to='anagrafiche.azienda')),
                ('contratto_generato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposta_origine', to='rapporto_di_lavoro.rapportodilavoro')),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposte_assunzione_create', to=settings.AUTH_USER_MODEL)),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte_assunzione', to='anagrafiche.dipendente')),
                ('modificato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposte_assunzione_modifica', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposte', to='rapporto_di_lavoro.modulocontrattuale')),
                ('parametro_ccnl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposte', to='rapporto_di_lavoro.parametroccnlturismo')),
                ('tipo_contratto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rapporto_di_lavoro.tipocontratto')),
            ],
            options={
                'verbose_name': 'Proposta Assunzione',
                'verbose_name_plural': 'Proposte Assunzione',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
