# Generated by Django 6.0.3 on 2026-03-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0002_modulocontrattuale_parametroccnlturismo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaassunzione',
            name='dichiarazione_conformita_legale',
            field=models.BooleanField(default=True, help_text='Conferma che la proposta è stata redatta in conformità al diritto del lavoro italiano e al CCNL applicato.'),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='riferimenti_normativi',
            field=models.TextField(default='La presente proposta è formulata nel rispetto della normativa italiana vigente in materia di lavoro, con particolare riferimento a: Costituzione della Repubblica Italiana (artt. 1, 4, 35, 36, 37, 38); Codice Civile, Libro V; D.Lgs. 81/2015 (disciplina organica dei contratti di lavoro); D.Lgs. 66/2003 (orario di lavoro); D.Lgs. 152/1997 e D.Lgs. 104/2022 (informazioni sul rapporto di lavoro); D.Lgs. 151/2001 (tutela maternità/paternità); D.Lgs. 198/2006 (pari opportunità); D.Lgs. 81/2008 (salute e sicurezza sul lavoro); normativa previdenziale e assicurativa INPS/INAIL; CCNL applicato indicato nella proposta.', help_text='Riferimenti normativi italiani applicati alla proposta.'),
        ),
    ]
