# Generated by Django 6.0.3 on 2026-03-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0003_propostaassunzione_dichiarazione_conformita_legale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='contingenza_mensile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='decorrenza_validita_a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='decorrenza_validita_da',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='edr_mensile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='numero_scatti_massimi',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='paga_base_mensile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='riposi_compensativi_regola',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='scatto_importo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='scatto_periodicita_mesi',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='straordinario_diurno_maggiorazione',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='straordinario_festivo_maggiorazione',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='parametroccnlturismo',
            name='straordinario_notturno_maggiorazione',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='contingenza_mensile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='decorrenza_validita_a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='decorrenza_validita_da',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='edr_mensile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='numero_scatti_massimi',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='paga_base_mensile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='riposi_compensativi_regola',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='scatto_importo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='scatto_periodicita_mesi',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='straordinario_diurno_maggiorazione',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='straordinario_festivo_maggiorazione',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='straordinario_notturno_maggiorazione',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='contingenza_mensile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='decorrenza_validita_a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='decorrenza_validita_da',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='edr_mensile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='numero_scatti_massimi',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='ore_straordinario_diurno_maggiorazione',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='ore_straordinario_festivo_maggiorazione',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='ore_straordinario_notturno_maggiorazione',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='paga_base_mensile',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='riposi_compensativi_regola',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='scatto_importo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='scatto_periodicita_mesi',
            field=models.IntegerField(default=24),
        ),
    ]
