# Generated by Django 6.0.3 on 2026-03-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0004_parametroccnlturismo_contingenza_mensile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontratto',
            name='coefficiente_ore',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Moltiplicatore per le ore (1.00=full-time, 0.50=50% part-time, ecc.)', max_digits=3),
        ),
        migrations.AddField(
            model_name='tipocontratto',
            name='tipo',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time_50', 'Part-time 50%'), ('part_time_60', 'Part-time 60%'), ('part_time_70', 'Part-time 70%'), ('part_time_80', 'Part-time 80%')], default='full_time', max_length=20),
        ),
    ]
