# Generated by Django 6.0.3 on 2026-03-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0005_tipocontratto_coefficiente_ore_tipocontratto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegolaNormativaCCNL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccnl', models.CharField(max_length=150)),
                ('versione', models.CharField(max_length=50)),
                ('sezione', models.CharField(choices=[('ristoranti_pizzerie', 'Ristoranti/Pizzerie con cucina'), ('somministrazione_tavoli', 'Somministrazione e servizio ai tavoli')], default='ristoranti_pizzerie', max_length=50)),
                ('livello', models.CharField(max_length=20)),
                ('decorrenza_validita_da', models.DateField(blank=True, null=True)),
                ('decorrenza_validita_a', models.DateField(blank=True, null=True)),
                ('ore_settimanali', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('ore_mensili', models.DecimalField(decimal_places=2, default=173.33, max_digits=6)),
                ('ore_giornaliere', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('ferie_annue_giorni', models.DecimalField(decimal_places=2, default=26, max_digits=5)),
                ('permessi_annui_ore', models.DecimalField(decimal_places=2, default=72, max_digits=6)),
                ('scatto_periodicita_mesi', models.IntegerField(default=36)),
                ('scatto_importo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_scatti_massimi', models.IntegerField(default=6)),
                ('note', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regola normativa CCNL',
                'verbose_name_plural': 'Regole normative CCNL',
                'ordering': ['ccnl', 'versione', 'sezione', 'livello', '-decorrenza_validita_da'],
                'unique_together': {('ccnl', 'versione', 'sezione', 'livello', 'decorrenza_validita_da')},
            },
        ),
    ]
