# Generated by Django 6.0.3 on 2026-03-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0010_aggiungi_eds_edb_irpef_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoceRetributiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text='Codice univoco (es: PAGA_BASE, SCATTO_ANZ, STRAORD_DIURNO)', max_length=50, unique=True)),
                ('nome', models.CharField(help_text='Denominazione completa della voce', max_length=200)),
                ('categoria', models.CharField(choices=[('minimo_tabellare', 'Paga base / Minimo tabellare'), ('contingenza', 'Contingenza / EDR'), ('scatto_anzianita', 'Scatto di anzianità'), ('superminimo', 'Superminimo'), ('indennita_funzione', 'Indennità di funzione/ruolo'), ('tredicesima', 'Tredicesima mensilità'), ('quattordicesima', 'Quattordicesima mensilità'), ('premio_risultato', 'Premio di risultato (tassazione ordinaria)'), ('premio_agevolato', 'Premio di risultato (tassazione agevolata 5%)'), ('straordinario', 'Straordinario / Maggiorazioni'), ('indennita_turno', 'Indennità di turno'), ('ferie_monetizzate', 'Ferie/permessi monetizzati'), ('preavviso', 'Indennità mancato preavviso'), ('trasferta', 'Trasferta (parzialmente esente)'), ('fringe_benefit', 'Fringe benefit (parzialmente esente)'), ('auto_aziendale', 'Auto aziendale uso promiscuo'), ('ticket_restaurant', 'Ticket restaurant / Buoni pasto'), ('rimborso_km', 'Rimborso km ACI (entro tabella)'), ('rimborso_documentato', 'Rimborso spese piè di lista'), ('bonus_fiscale', 'Bonus fiscale non imponibile (TI/L207)'), ('previdenza_complementare', 'Contributo fondo pensione azienda'), ('incentivo_esodo', "Incentivo all'esodo (tass. separata)"), ('altro', 'Altra voce')], default='altro', max_length=50)),
                ('imponibile_inps', models.BooleanField(default=True, help_text='Se True, concorre alla base imponibile INPS')),
                ('imponibile_inail', models.BooleanField(default=True, help_text='Se True, concorre alla base imponibile INAIL')),
                ('imponibile_irpef', models.BooleanField(default=True, help_text='Se True, concorre alla base imponibile IRPEF')),
                ('imponibile_parziale', models.BooleanField(default=False, help_text='Se True, la voce è imponibile solo per la parte eccedente la franchigia. Collegare il campo codice_franchigia al relativo FranchigiaSogliaVoce.')),
                ('codice_franchigia', models.CharField(blank=True, help_text='Codice FranchigiaSogliaVoce da applicare (se imponibile_parziale=True)', max_length=50)),
                ('aliquota_agevolata', models.DecimalField(blank=True, decimal_places=2, help_text='Aliquota sostitutiva % IRPEF (es: 5.00 per premi risultato agevolati)', max_digits=5, null=True)),
                ('importo_massimo_agevolato_annuo', models.DecimalField(blank=True, decimal_places=2, help_text="Importo massimo annuo soggetto all'aliquota agevolata (es: 3000 €)", max_digits=12, null=True)),
                ('descrizione', models.TextField(blank=True)),
                ('riferimento_normativo', models.CharField(blank=True, help_text='Es: art. 51 TUIR c. 3 — Fringe benefit', max_length=300)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voce retributiva',
                'verbose_name_plural': 'Voci retributive',
                'ordering': ['categoria', 'codice'],
            },
        ),
        migrations.RemoveField(
            model_name='parametroccnlturismo',
            name='eds_edb_su_base_oraria',
        ),
        migrations.AlterField(
            model_name='parametroccnlturismo',
            name='elemento_distinto_bilateralita',
            field=models.DecimalField(decimal_places=5, default=0, help_text='EDB - Elemento Distinto Bilateralità (€/ora)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametroccnlturismo',
            name='elemento_distinto_sanita',
            field=models.DecimalField(decimal_places=5, default=0, help_text='EDS - Elemento Distinto Sanità (€/ora)', max_digits=10),
        ),
        migrations.CreateModel(
            name='FranchigiaSogliaVoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text='Codice univoco (es: TRASFERTA_ITA_2025, FB_FIGLI_2025)', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('trasferta_italia', 'Trasferta Italia — diaria giornaliera'), ('trasferta_estero', 'Trasferta Estero — diaria giornaliera'), ('fringe_benefit_generale', 'Fringe benefit — soglia annua (senza figli)'), ('fringe_benefit_con_figli', 'Fringe benefit — soglia annua (con figli a carico)'), ('ticket_cartaceo', 'Ticket restaurant cartaceo — giornaliero'), ('ticket_elettronico', 'Ticket restaurant elettronico — giornaliero'), ('rimborso_km_aci', 'Rimborso km ACI — per km (entro tabella)'), ('altro', 'Altra franchigia')], max_length=50)),
                ('anno', models.IntegerField(help_text='Anno fiscale di riferimento')),
                ('importo', models.DecimalField(decimal_places=2, help_text='Importo soglia esente per unità di misura indicata', max_digits=12)),
                ('unita_misura', models.CharField(choices=[('giorno', 'Per giorno'), ('anno', 'Per anno'), ('km', 'Per km'), ('pasto', 'Per pasto'), ('mese', 'Per mese')], default='giorno', help_text='Unità di misura della soglia (giorno, anno, km, pasto)', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('riferimento_normativo', models.CharField(blank=True, help_text='Es: art. 51 c. 5 TUIR — L. 213/2023 art. 1 c. 16', max_length=300)),
                ('data_validita_da', models.DateField()),
                ('data_validita_a', models.DateField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Franchigia / Soglia voce retributiva',
                'verbose_name_plural': 'Franchigie / Soglie voci retributive',
                'ordering': ['-anno', 'tipo'],
                'unique_together': {('tipo', 'anno')},
            },
        ),
        migrations.CreateModel(
            name='InailParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(help_text='Anno di riferimento')),
                ('retribuzione_giornaliera_minima', models.DecimalField(decimal_places=2, help_text='Minimale retribuzione giornaliera INAIL: se la retribuzione effettiva giornaliera è inferiore a questo importo, si usa questo valore per il calcolo del premio (circ. INAIL annuale)', max_digits=10)),
                ('retribuzione_giornaliera_massima', models.DecimalField(blank=True, decimal_places=2, help_text='Massimale retribuzione giornaliera INAIL (opzionale)', max_digits=10, null=True)),
                ('retribuzione_annua_massima', models.DecimalField(blank=True, decimal_places=2, help_text='Massimale annuo retribuzione imponibile INAIL (opzionale)', max_digits=12, null=True)),
                ('retribuzione_convenzionale_giornaliera', models.DecimalField(blank=True, decimal_places=2, help_text='Retribuzione convenzionale giornaliera per categorie speciali (es. lavoratori con part-time molto ridotto)', max_digits=10, null=True)),
                ('data_validita_da', models.DateField()),
                ('data_validita_a', models.DateField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('ccnl', models.ForeignKey(help_text='CCNL di riferimento', on_delete=django.db.models.deletion.CASCADE, related_name='parametri_inail', to='rapporto_di_lavoro.ccnl')),
            ],
            options={
                'verbose_name': 'Parametro INAIL massimale/minimale',
                'verbose_name_plural': 'Parametri INAIL massimali/minimali',
                'ordering': ['ccnl', '-anno'],
                'unique_together': {('ccnl', 'anno', 'data_validita_da')},
            },
        ),
    ]
