# Generated by Django 6.0.3 on 2026-03-14 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_azienda_configurazione_contrattuale'),
        ('rapporto_di_lavoro', '0011_voce_retributiva_franchigia_inail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiepilogoMensileDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('mese', models.IntegerField(help_text='1=gennaio ... 12=dicembre')),
                ('data_competenza', models.DateField(help_text='Primo giorno del mese di competenza')),
                ('imponibile_inps', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imponibile_inail', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imponibile_irpef', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inps_dipendente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('irpef_lorda', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detrazioni', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('irpef_netta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('addizionale_regionale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('addizionale_comunale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inps_azienda', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inail', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trattamento_integrativo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_l207_2024', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('netto_da_pagare_dipendente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('decontribuzione_inps', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('crediti_inps', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('crediti_inail', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('crediti_erario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('versamento_inps_lordo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('versamento_inps_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('versamento_inail_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('versamento_erario_netto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rateo_tredicesima', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rateo_quattordicesima', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tfr_mensile', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ratei_concorsi_in_imponibile', models.BooleanField(default=False)),
                ('imposte_aggiuntive_ratei_dipendente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imposte_aggiuntive_ratei_azienda', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imposte_aggiuntive_ratei_erario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accantonamenti_lordi_mese', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accantonamenti_netti_stimati_mese', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esborso_totale_azienda_mese', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riepiloghi_mensili_dipendenti', to='anagrafiche.azienda')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riepiloghi_mensili', to='anagrafiche.dipendente')),
            ],
            options={
                'verbose_name': 'Riepilogo mensile dipendente',
                'verbose_name_plural': 'Riepiloghi mensili dipendenti',
                'ordering': ['-anno', '-mese', 'dipendente__cognome', 'dipendente__nome'],
                'unique_together': {('dipendente', 'anno', 'mese')},
            },
        ),
    ]
