# Generated by Django 6.0.3 on 2026-03-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_azienda_configurazione_contrattuale'),
        ('rapporto_di_lavoro', '0012_riepilogo_mensile_dipendente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiusuraAziendale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('trattamento', models.CharField(choices=[('ferie', 'Ferie'), ('riposo_compensativo', 'Riposo compensativo'), ('lavoro_normale', 'Lavoro normale per esigenze aziendali'), ('chiusura_non_retribuita', 'Chiusura non retribuita')], default='ferie', max_length=30)),
                ('descrizione', models.CharField(blank=True, max_length=200)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiusure_aziendali', to='anagrafiche.azienda')),
            ],
            options={
                'verbose_name': 'Chiusura aziendale',
                'verbose_name_plural': 'Chiusure aziendali',
                'ordering': ['-data_inizio'],
            },
        ),
        migrations.CreateModel(
            name='FestivitaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=120)),
                ('livello', models.CharField(choices=[('nazionale', 'Nazionale'), ('regionale', 'Regionale'), ('provinciale', 'Provinciale'), ('comunale', 'Comunale'), ('aziendale', 'Aziendale')], default='nazionale', max_length=20)),
                ('regione', models.CharField(blank=True, max_length=80)),
                ('provincia', models.CharField(blank=True, max_length=10)),
                ('comune', models.CharField(blank=True, max_length=80)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Festività calendario',
                'verbose_name_plural': 'Festività calendario',
                'ordering': ['data', 'livello', 'nome'],
                'unique_together': {('data', 'nome', 'livello', 'regione', 'provincia', 'comune')},
            },
        ),
        migrations.CreateModel(
            name='CalendarioPresenzeDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese_riferimento', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('ruolo_riferimento', models.CharField(blank=True, help_text='Chiave ruolo simulato (es. ruolo_1)', max_length=80)),
                ('giorni_presenza', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('giorni_assenza', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('giorni_ferie', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('giorni_riposo_compensativo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ore_straordinario_diurno', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ore_straordinario_notturno', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ore_straordinario_festivo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ore_lavoro_domenicale', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ore_lavoro_festivo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('applica_chiusure_aziendali', models.BooleanField(default=True)),
                ('includi_ratei_nel_netto', models.BooleanField(default=False)),
                ('giorni_json', models.JSONField(blank=True, default=list, help_text='Dettaglio giornaliero opzionale per integrazioni future')),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendari_presenze', to='anagrafiche.azienda')),
                ('dipendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendari_presenze', to='anagrafiche.dipendente')),
            ],
            options={
                'verbose_name': 'Calendario presenze dipendente',
                'verbose_name_plural': 'Calendari presenze dipendenti',
                'ordering': ['-mese_riferimento', 'azienda', 'dipendente__cognome', 'ruolo_riferimento'],
                'constraints': [models.UniqueConstraint(fields=('azienda', 'dipendente', 'mese_riferimento'), name='uniq_cal_presenze_azienda_dip_mese'), models.UniqueConstraint(condition=models.Q(('ruolo_riferimento', ''), _negated=True), fields=('azienda', 'ruolo_riferimento', 'mese_riferimento'), name='uniq_cal_presenze_azienda_ruolo_mese')],
            },
        ),
    ]
