# Generated by Django 6.0.3 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0013_chiusuraaziendale_festivitacalendario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocontratto',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('full_time', 'Full-time'),
                    ('part_time_50', 'Part-time 50%'),
                    ('part_time_60', 'Part-time 60%'),
                    ('part_time_70', 'Part-time 70%'),
                    ('part_time_80', 'Part-time 80%'),
                    ('part_time_90', 'Part-time 90%'),
                ],
                default='full_time',
                max_length=20,
            ),
        ),
    ]
