# Generated by GitHub Copilot on 2026-03-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_azienda_configurazione_contrattuale'),
        ('rapporto_di_lavoro', '0014_tipocontratto_part_time_90'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulazioneVoceRetributivaOre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese_riferimento', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('ruolo_id', models.CharField(help_text='Chiave ruolo simulato (es. cuoco, cameriere1)', max_length=80)),
                ('ruolo_label', models.CharField(blank=True, max_length=120)),
                ('dipendente_nome', models.CharField(blank=True, max_length=150)),
                ('voce', models.CharField(choices=[
                    ('minimo_tabellare', 'Minimo tabellare'),
                    ('contingenza', 'Contingenza'),
                    ('el_dis_san', 'EL.DIS.SAN'),
                    ('scatto_anzianita', 'Scatto anzianità'),
                    ('superminimo', 'Superminimo'),
                    ('el_dis_bil', 'EL.DIS.BIL'),
                ], max_length=30)),
                ('presente', models.BooleanField(default=False)),
                ('importo_lordo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci_retributive_ore', to='anagrafiche.azienda')),
                ('simulazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci_retributive_ore', to='rapporto_di_lavoro.simulazioneorganico')),
            ],
            options={
                'verbose_name': 'Simulazione voce retributiva (ore)',
                'verbose_name_plural': 'Simulazione voci retributive (ore)',
                'ordering': ['-data_modifica', 'ruolo_id', 'voce'],
                'unique_together': {('simulazione', 'ruolo_id', 'voce')},
            },
        ),
    ]
