# Generated by GitHub Copilot on 2026-03-15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def _seed_parametri_voci(apps, schema_editor):
    ParametroCCNLTurismo = apps.get_model('rapporto_di_lavoro', 'ParametroCCNLTurismo')
    VoceRetributiva = apps.get_model('rapporto_di_lavoro', 'VoceRetributiva')
    ParametroVoceRetributiva = apps.get_model('rapporto_di_lavoro', 'ParametroVoceRetributiva')

    voci_spec = [
        ('MINIMO_TABELLARE', 'Minimo tabellare', 'minimo_tabellare'),
        ('CONTINGENZA', 'Contingenza', 'contingenza'),
        ('SCATTO_ANZIANITA', 'Scatto anzianità', 'scatto_anzianita'),
        ('SUPERMINIMO', 'Superminimo', 'superminimo'),
        ('EL_DIS_SAN', 'Elemento distinto sanità', 'altro'),
        ('EL_DIS_BIL', 'Elemento distinto bilateralità', 'altro'),
    ]

    voci = {}
    for codice, nome, categoria in voci_spec:
        voce, _ = VoceRetributiva.objects.get_or_create(
            codice=codice,
            defaults={
                'nome': nome,
                'categoria': categoria,
                'imponibile_inps': True,
                'imponibile_inail': True,
                'imponibile_irpef': True,
                'attivo': True,
            },
        )
        voci[codice] = voce

    for p in ParametroCCNLTurismo.objects.all():
        anno = p.decorrenza_validita_da.year if p.decorrenza_validita_da else 2026

        def upsert(codice, importo_mensile=0, importo_orario=0):
            ParametroVoceRetributiva.objects.update_or_create(
                voce=voci[codice],
                ccnl=p.ccnl,
                versione=p.versione,
                sezione=p.sezione,
                livello=p.livello,
                anno=anno,
                defaults={
                    'importo_mensile': importo_mensile or 0,
                    'importo_orario': importo_orario or 0,
                    'data_validita_da': p.decorrenza_validita_da,
                    'data_validita_a': p.decorrenza_validita_a,
                    'attivo': bool(p.attivo),
                },
            )

        minimo = p.minimo_tabellare or p.paga_base_mensile or 0
        upsert('MINIMO_TABELLARE', importo_mensile=minimo)
        upsert('CONTINGENZA', importo_mensile=p.contingenza_mensile or 0)
        upsert('SCATTO_ANZIANITA', importo_mensile=p.scatto_importo or 0)
        upsert('SUPERMINIMO', importo_mensile=getattr(p, 'superminimo_mensile', 0) or 0)
        upsert('EL_DIS_SAN', importo_orario=p.elemento_distinto_sanita or 0)
        upsert('EL_DIS_BIL', importo_orario=p.elemento_distinto_bilateralita or 0)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0015_simulazionevoceretributivaore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroVoceRetributiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccnl', models.CharField(default='Turismo Confcommercio', max_length=150)),
                ('versione', models.CharField(default='2024-2026', max_length=50)),
                ('sezione', models.CharField(choices=[('ristoranti_pizzerie', 'Ristoranti/Pizzerie con cucina'), ('somministrazione_tavoli', 'Somministrazione e servizio ai tavoli')], default='ristoranti_pizzerie', max_length=50)),
                ('livello', models.CharField(max_length=20)),
                ('anno', models.IntegerField(default=2026)),
                ('importo_mensile', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('importo_orario', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=12)),
                ('data_validita_da', models.DateField(blank=True, null=True)),
                ('data_validita_a', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametri_valore', to='rapporto_di_lavoro.voceretributiva')),
            ],
            options={
                'verbose_name': 'Parametro voce retributiva',
                'verbose_name_plural': 'Parametri voci retributive',
                'ordering': ['ccnl', 'versione', 'sezione', 'livello', 'voce__codice', '-anno'],
                'unique_together': {('voce', 'ccnl', 'versione', 'sezione', 'livello', 'anno')},
            },
        ),
        migrations.RunPython(_seed_parametri_voci, _noop_reverse),
    ]
