# Generated by Django 6.0.3 on 2026-03-17 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_azienda_configurazione_contrattuale'),
        ('rapporto_di_lavoro', '0018_ruoloorganico2026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='festivitacalendario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='festivitacalendario',
            name='azienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festivita_aziendali', to='anagrafiche.azienda'),
        ),
        migrations.AlterField(
            model_name='ruoloorganico2026',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='festivitacalendario',
            unique_together={('data', 'nome', 'livello', 'regione', 'provincia', 'comune', 'azienda')},
        ),
        migrations.CreateModel(
            name='CalendarioLavoroMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField()),
                ('mese', models.PositiveSmallIntegerField(choices=[(1, 'Gennaio'), (2, 'Febbraio'), (3, 'Marzo'), (4, 'Aprile'), (5, 'Maggio'), (6, 'Giugno'), (7, 'Luglio'), (8, 'Agosto'), (9, 'Settembre'), (10, 'Ottobre'), (11, 'Novembre'), (12, 'Dicembre')])),
                ('chiusura_settimanale', models.JSONField(default=list, help_text='Lista di interi: 0=Lun, 1=Mar, 2=Mer, 3=Gio, 4=Ven, 5=Sab, 6=Dom')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario_lavoro_mensile', to='anagrafiche.azienda')),
            ],
            options={
                'verbose_name': 'Calendario lavoro mensile',
                'verbose_name_plural': 'Calendari lavoro mensili',
                'ordering': ['anno', 'mese'],
                'unique_together': {('azienda', 'anno', 'mese')},
            },
        ),
    ]
