# Generated by Django 6.0.3 on 2026-03-22 10:32

import rapporto_di_lavoro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0021_remove_variazione_contratto'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaassunzione',
            name='giorni_ferie_annuali',
            field=models.IntegerField(default=26, help_text='Giorni di ferie annue spettanti (art. 7 D.Lgs. 66/2003)'),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='giorni_permesso_annuali',
            field=models.IntegerField(default=3, help_text='Giorni di permesso retribuito annui (CCNL)'),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='quattordicesima',
            field=models.BooleanField(default=False, help_text='Mensilità aggiuntiva pagata a luglio (CCNL FIPE turismo)'),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='tredicesima',
            field=models.BooleanField(default=True, help_text='Mensilità aggiuntiva pagata a dicembre (CCNL FIPE)'),
        ),
        migrations.AlterField(
            model_name='parametroratei',
            name='tipo_rateo',
            field=models.CharField(choices=[('tfr', 'TFR (Trattamento Fine Rapporto)'), ('tredicesima', 'Tredicesima mensilità'), ('quattordicesima', 'Quattordicesima mensilità'), ('ferie', 'Rateo ferie'), ('permessi', 'Rateo permessi / ROL'), ('indennita_ferie', 'Indennità ferie non godute'), ('indennita_licenziamento', 'Indennità licenziamento'), ('preavviso', 'Preavviso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parametrovoceretributiva',
            name='anno',
            field=models.IntegerField(default=rapporto_di_lavoro.models._anno_corrente),
        ),
        migrations.AlterField(
            model_name='tipocontratto',
            name='tipo',
            field=models.CharField(choices=[('ind_full', 'Indeterminato full-time'), ('ind_pt_50', 'Indeterminato part-time 50%'), ('ind_pt_60', 'Indeterminato part-time 60%'), ('ind_pt_75', 'Indeterminato part-time 75%'), ('ind_pt_80', 'Indeterminato part-time 80%'), ('ind_pt_83', 'Indeterminato part-time 83%'), ('det_full', 'Determinato full-time'), ('det_pt_50', 'Determinato part-time 50%'), ('det_pt_75', 'Determinato part-time 75%'), ('stag_full', 'Stagionale full-time'), ('stag_pt', 'Stagionale part-time'), ('apprendistato', 'Apprendistato professionalizzante'), ('intermittente', 'Lavoro intermittente / a chiamata'), ('somministrazione', 'Somministrazione')], default='full_time', max_length=20),
        ),
    ]
