# Generated by Django 6.0.3 on 2026-03-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0022_proposta_tredicesima_quattordicesima_ferie_permessi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMotorePaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_test', models.CharField(help_text='Es. "Cameriere L4 full-time marzo 2026 — verifica TI e bonus L207"', max_length=150, verbose_name='Nome scenario di test')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza — parametri da compilare'), ('calcolato', 'Calcolato — risultati disponibili')], default='bozza', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='Note e osservazioni')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('mese_riferimento', models.CharField(help_text='Formato YYYY-MM — es. 2026-03', max_length=7, verbose_name='Mese di riferimento (YYYY-MM)')),
                ('data_inizio_rapporto', models.DateField(blank=True, help_text='Se nel mese di riferimento → calcola il pro-rata (regola CCNL: ≥15 gg = mese intero)', null=True, verbose_name='Data inizio rapporto')),
                ('divisore', models.IntegerField(choices=[(26, '26 — CCNL FIPE (riferimento mensile convenzionale)'), (30, '30 — Mese civile (30 giorni fissi)')], default=26, help_text='Usato per calcolare la paga giornaliera (lordo ÷ divisore)', verbose_name='Divisore convenzionale')),
                ('giorni_lavorativi_settimana', models.IntegerField(choices=[(5, '5 giorni — Lun–Ven'), (6, '6 giorni — Lun–Sab (CCNL FIPE ristorazione)'), (7, '7 giorni — ciclo continuo')], default=6, verbose_name='Giorni lavorativi/settimana')),
                ('giorni_chiusura_mese', models.IntegerField(default=0, help_text='Giorni di chiusura (non lavorativi non retribuiti) da escludere', verbose_name='Giorni di chiusura aziendale nel mese')),
                ('superminimo', models.DecimalField(decimal_places=2, default=0, help_text='Voce aggiuntiva concordata individualmente — imponibile INPS e IRPEF', max_digits=8, verbose_name='Superminimo individuale (€/mese)')),
                ('indennita_turno', models.DecimalField(decimal_places=2, default=0, help_text='Voce aggiuntiva — imponibile INPS e IRPEF', max_digits=8, verbose_name='Indennità di turno/reperibilità (€/mese)')),
                ('altre_voci_json', models.JSONField(blank=True, default=dict, help_text='Dizionario {"nome_voce": importo, ...} per voci extra da testare', verbose_name='Altre voci retributive (JSON)')),
                ('r_lordo_pieno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lordo mensile pieno (€)')),
                ('r_lordo_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lordo mensile pro-rata (€)')),
                ('r_giorni_lavorati', models.IntegerField(blank=True, null=True, verbose_name='Giorni lavorati nel mese')),
                ('r_giorni_mese', models.IntegerField(blank=True, null=True, verbose_name='Giorni totali nel mese')),
                ('r_paga_giornaliera', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Paga giornaliera (lordo ÷ divisore)')),
                ('r_paga_oraria', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Paga oraria (€/h)')),
                ('r_paga_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Paga base (€)')),
                ('r_contingenza', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Contingenza (€)')),
                ('r_edr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EDR (€)')),
                ('r_indennita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Indennità mensile CCNL (€)')),
                ('r_superminimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superminimo (€)')),
                ('r_indennita_turno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Indennità turno (€)')),
                ('r_altre_voci', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altre voci (€)')),
                ('r_inps_dip_perc', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Aliquota INPS dipendente (%)')),
                ('r_inps_az_perc', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Aliquota INPS azienda (%)')),
                ('r_inps_dipendente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='INPS c/dipendente (€)')),
                ('r_inps_azienda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='INPS c/azienda (€)')),
                ('r_inail_azienda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='INAIL c/azienda (€)')),
                ('r_imponibile_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Imponibile IRPEF mensile (€)')),
                ('r_imponibile_annuo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Imponibile IRPEF annuo stimato (€)')),
                ('r_irpef_lorda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IRPEF lorda mensile (€)')),
                ('r_detrazioni', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Detrazioni lavoro dipendente (€)')),
                ('r_irpef_netta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IRPEF netta mensile (€)')),
                ('r_netto_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Netto base (lordo − INPS − IRPEF)')),
                ('r_trattamento_integrativo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Trattamento Integrativo DL 3/2020 (€)')),
                ('r_bonus_l207', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bonus L. 207/2024 (€)')),
                ('r_netto_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='NETTO MENSILE IN BUSTA (€)')),
                ('r_addiz_reg_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Add. regionale mensile stimata (€)')),
                ('r_addiz_com_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Add. comunale mensile stimata (€)')),
                ('r_addiz_totale_annuo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Addizionali totali annue stimate (€)')),
                ('r_tfr_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='TFR accantonato mensile (€)')),
                ('r_rateo_13_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Rateo 13ª mensile (€)')),
                ('r_rateo_14_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Rateo 14ª mensile (€)')),
                ('r_rateo_ferie_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Rateo ferie mensile (€)')),
                ('r_f24_inps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='F24 INPS totale (az + dip, €)')),
                ('r_f24_erario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='F24 Erario (IRPEF − TI − L207, €)')),
                ('r_costo_totale_azienda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo totale azienda mensile (€)')),
                ('r_costo_annuo_stimato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo annuo stimato (€)')),
                ('risultato_json', models.JSONField(blank=True, default=dict, verbose_name='Risultato completo (JSON)')),
                ('parametro_ccnl', models.ForeignKey(help_text='Seleziona il livello di riferimento — tutte le voci vengono lette da questa tabella', on_delete=django.db.models.deletion.PROTECT, to='rapporto_di_lavoro.parametroccnlturismo', verbose_name='Livello CCNL')),
                ('tipo_contratto', models.ForeignKey(help_text='Full-time (100%) o Part-time con coefficiente orario ridotto', on_delete=django.db.models.deletion.PROTECT, to='rapporto_di_lavoro.tipocontratto', verbose_name='Tipo di contratto / orario')),
            ],
            options={
                'verbose_name': 'Test Motore Paga',
                'verbose_name_plural': 'Test Motore Paga — Sandbox',
                'ordering': ['-data_modifica'],
            },
        ),
    ]
