# Generated by Django 6.0.3 on 2026-03-24 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0023_test_motore_paga_sandbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulazionePagaSalvata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome scenario')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='Ultima modifica')),
                ('anno', models.IntegerField(verbose_name='Anno')),
                ('mese', models.IntegerField(verbose_name='Mese')),
                ('ccnl_livello', models.CharField(blank=True, max_length=50, verbose_name='Livello CCNL')),
                ('ccnl_qualifica', models.CharField(blank=True, max_length=200, verbose_name='Qualifica CCNL')),
                ('tipo_contratto_nome', models.CharField(blank=True, max_length=100, verbose_name='Tipo contratto')),
                ('lordo_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lordo mensile (€)')),
                ('netto_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Netto in busta (€)')),
                ('costo_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo azienda mensile (€)')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='Parametri form')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulazioni_paga', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Simulazione Paga Salvata',
                'verbose_name_plural': 'Simulazioni Paga Salvate',
                'ordering': ['-data_modifica'],
            },
        ),
    ]
