# Generated by Django 6.0.3 on 2026-03-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0027_firme_luogo_data_ora'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaassunzione',
            name='mansionario_file',
            field=models.FileField(blank=True, help_text='Allega il mansionario specifico per la mansione (PDF, facoltativo)', null=True, upload_to='contratti/mansionari/', verbose_name='Mansionario allegato'),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='mansionario_file',
            field=models.FileField(blank=True, help_text='Allega il mansionario specifico per la mansione (PDF, facoltativo)', null=True, upload_to='contratti/mansionari/', verbose_name='Mansionario allegato'),
        ),
    ]
