# Generated by Django 6.0.3 on 2026-04-18 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0032_alter_tipocontratto_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddendumContrattuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rinnovo_td', 'Rinnovo o proroga a tempo determinato'), ('trasformazione', 'Trasformazione (es. TD → TI)'), ('variazione_retribuzione', 'Variazione retribuzione o livello CCNL'), ('variazione_orario', 'Variazione orario o part-time'), ('altro', 'Altro (specificare nelle note)')], default='altro', max_length=40)),
                ('data_decorrenza', models.DateField(help_text="Data efficacia dell'atto rispetto al contratto originario.", verbose_name='Decorrenza')),
                ('data_fine_rapporto_aggiornata', models.DateField(blank=True, help_text='Es. nuova scadenza dopo rinnovo TD; lasciare vuoto se invariata.', null=True, verbose_name='Nuova data fine rapporto')),
                ('stipendio_lordo_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='RAL mensile lorda (riferimento)')),
                ('paga_base_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contingenza_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('edr_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ore_settimanali', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('livello_ccnl', models.CharField(blank=True, max_length=50, verbose_name='Livello CCNL')),
                ('qualifica', models.CharField(blank=True, max_length=100)),
                ('riferimento_atto', models.CharField(blank=True, max_length=120, verbose_name='Riferimento atto / protocollo')),
                ('note', models.TextField(blank=True)),
                ('file_allegato', models.FileField(blank=True, null=True, upload_to='contratti/addenda/', verbose_name='Allegato (PDF atto, lettera, ecc.)')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addenda_contrattuali_creati', to=settings.AUTH_USER_MODEL)),
                ('parametro_ccnl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapporto_di_lavoro.parametroccnlturismo', verbose_name='Parametro CCNL (riferimento tabellare)')),
                ('rapporto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='rapporto_di_lavoro.rapportodilavoro', verbose_name='Contratto di riferimento')),
                ('tipo_contratto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapporto_di_lavoro.tipocontratto', verbose_name='Tipo contratto')),
            ],
            options={
                'verbose_name': 'Addendum contrattuale',
                'verbose_name_plural': 'Addendum contrattuali',
                'ordering': ['-data_decorrenza', '-data_creazione', '-id'],
            },
        ),
    ]
