# Generated by Django 6.0.3 on 2026-04-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0033_addendum_contrattuale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametromaggiorazione',
            name='tipo_maggiorazione',
            field=models.CharField(choices=[('straordinario_feriale', 'Straordinario feriale'), ('straordinario_festivo', 'Straordinario festivo'), ('straordinario_domenicale', 'Straordinario domenicale'), ('straordinario_notturno', 'Straordinario notturno'), ('straordinario_notturno_festivo', 'Straordinario notturno festivo'), ('lavoro_festivo', 'Lavoro festivo'), ('lavoro_domenicale', 'Lavoro domenicale'), ('lavoro_notturno', 'Lavoro notturno'), ('lavoro_supplementare_part_time', 'Lavoro supplementare part-time')], max_length=50),
        ),
    ]
