# Generated by Django 6.0.3 on 2026-04-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0036_ruoloorganico2026_soggetto_fields_reset_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaassunzione',
            name='superminimo_mensile',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importo retributivo concordato oltre i minimi tabellari CCNL (€/mese, imponibile). Entra in tredicesima/quattordicesima, TFR, INPS, ferie/permessi, malattia/maternità e trattamento economico; non è bonus una tantum — resta stabile fino a modifica.', max_digits=10, verbose_name='Superminimo mensile'),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='superminimo_mensile',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importo retributivo concordato oltre i minimi tabellari CCNL (€/mese, imponibile). Entra in tredicesima/quattordicesima, TFR, INPS, ferie/permessi, malattia/maternità e trattamento economico; non è bonus una tantum — resta stabile fino a modifica contrattuale.', max_digits=10, verbose_name='Superminimo mensile'),
        ),
    ]
