# Generated by Django 6.0.3 on 2026-04-26 07:20

import django.db.models.deletion
from django.db import migrations, models


def seed_mappature_voci_motore(apps, schema_editor):
    MappaturaVoceMotore = apps.get_model('rapporto_di_lavoro', 'MappaturaVoceMotore')
    VoceRetributiva = apps.get_model('rapporto_di_lavoro', 'VoceRetributiva')
    righe = [
        ('MINIMO_TABELLARE', 1, True, True, True, True, True, True, 'Paga base / minimo tabellare', ''),
        ('CONTINGENZA', 2, True, True, True, True, True, True, 'Contingenza + EDR (aggregato motore)', ''),
        ('IND_FUNZIONE', 3, True, True, True, True, True, True, 'Indennità contrattuali / funzione', ''),
        ('SUPERMINIMO', 4, True, True, True, True, True, True, 'Superminimo', ''),
        ('SCATTO_ANZIANITA', 5, True, True, True, True, True, True, 'Scatti anzianità', ''),
        ('IND_TURNO', 6, True, True, True, True, True, True, 'Indennità di turno', ''),
        ('STRAORD_DIURNO', 10, True, True, True, False, False, False, 'Straordinario diurno', 'Non matura 13ª/14ª; escluso da TFR'),
        ('STRAORD_NOTTURNO', 11, True, True, True, False, False, False, 'Straordinario notturno', 'Non matura 13ª/14ª; escluso da TFR'),
        ('STRAORD_FESTIVO', 12, True, True, True, False, False, False, 'Straord. festivo / nott. fest.', 'Non matura 13ª/14ª; escluso da TFR'),
        ('STRAORD_DOMENICA', 13, True, True, True, False, False, False, 'Straord. domenicale', 'Non matura 13ª/14ª; escluso da TFR'),
        ('MAGG_DOM_FEST', 14, True, True, True, True, True, True, 'Magg. domenica/festivo (non straord.)', 'Matura 13ª/14ª; concorre TFR'),
        ('TI_DL3_2020', 50, False, False, False, False, False, False, 'Trattamento integrativo', "Credito d'imposta — fuori INPS"),
        ('BONUS_L207_2024', 51, False, False, False, False, False, False, 'Bonus L.207/2024', 'Fuori INPS; detrazione/credito IRPEF'),
        ('TREDICESIMA', 80, True, True, True, False, False, True, 'Rateo 13ª lordo', 'Base INPS; non concorre a nuova maturazione 13ª'),
        ('QUATTORDICESIMA', 81, True, True, True, False, False, True, 'Rateo 14ª lordo', 'Base INPS; non concorre a nuova maturazione 14ª'),
    ]
    for (
        codice,
        ordine,
        inps,
        inail,
        irpef,
        m13,
        m14,
        tfr,
        etichetta,
        note,
    ) in righe:
        vr = VoceRetributiva.objects.filter(codice=codice, attivo=True).first()
        MappaturaVoceMotore.objects.update_or_create(
            codice_voce=codice,
            defaults={
                'voce_retributiva': vr,
                'ordine_calcolo': ordine,
                'imponibile_inps': inps,
                'imponibile_inail': inail,
                'imponibile_irpef': irpef,
                'matura_tredicesima': m13,
                'matura_quattordicesima': m14,
                'concorre_tfr': tfr,
                'etichetta_riconciliazione': etichetta[:200],
                'note_riconciliazione': note,
                'attivo': True,
            },
        )


def unseed_mappature_voci_motore(apps, schema_editor):
    MappaturaVoceMotore = apps.get_model('rapporto_di_lavoro', 'MappaturaVoceMotore')
    MappaturaVoceMotore.objects.filter(
        codice_voce__in=[
            'MINIMO_TABELLARE', 'CONTINGENZA', 'IND_FUNZIONE', 'SUPERMINIMO', 'SCATTO_ANZIANITA',
            'IND_TURNO', 'STRAORD_DIURNO', 'STRAORD_NOTTURNO', 'STRAORD_FESTIVO', 'STRAORD_DOMENICA',
            'MAGG_DOM_FEST', 'TI_DL3_2020', 'BONUS_L207_2024', 'TREDICESIMA', 'QUATTORDICESIMA',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0037_rappro_superminimo_mensile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappaturaVoceMotore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_voce', models.CharField(db_index=True, help_text='Codice univoco allineato al motore (es. MINIMO_TABELLARE, MAGG_DOM_FEST, STRAORD_DIURNO).', max_length=50, unique=True)),
                ('ordine_calcolo', models.PositiveSmallIntegerField(default=99, help_text='Ordine di presentazione / schema (1 = paga base oraria, …).')),
                ('imponibile_inps', models.BooleanField(default=True)),
                ('imponibile_inail', models.BooleanField(default=True)),
                ('imponibile_irpef', models.BooleanField(default=True)),
                ('matura_tredicesima', models.BooleanField(default=True)),
                ('matura_quattordicesima', models.BooleanField(default=True)),
                ('concorre_tfr', models.BooleanField(default=True)),
                ('etichetta_riconciliazione', models.CharField(blank=True, help_text='Es. etichetta busta paga / cedolino TeamSystem per controllo incrociato.', max_length=200, verbose_name='Etichetta riconciliazione')),
                ('note_riconciliazione', models.TextField(blank=True, help_text='Riferimenti normativi o regole aziendali applicate alla voce.', verbose_name='Note per riconciliazione')),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('voce_retributiva', models.ForeignKey(blank=True, help_text='Opzionale: collega alla scheda VoceRetributiva omonima o correlata.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappature_motore', to='rapporto_di_lavoro.voceretributiva', verbose_name='Voce retributiva (anagrafica)')),
            ],
            options={
                'verbose_name': 'Mappatura voce motore paga',
                'verbose_name_plural': 'Mappature voci motore paga',
                'ordering': ['ordine_calcolo', 'codice_voce'],
            },
        ),
        migrations.RunPython(seed_mappature_voci_motore, unseed_mappature_voci_motore),
    ]
