# Generated by Django 6.0.3

from django.db import migrations, models


def forwards_set_ratei_imponibile_da_contratto(apps, schema_editor):
    RapportoDiLavoro = apps.get_model('rapporto_di_lavoro', 'RapportoDiLavoro')
    PropostaAssunzione = apps.get_model('rapporto_di_lavoro', 'PropostaAssunzione')
    # Comportamento precedente: ratei mensili nella base INPS se la mensilità è prevista.
    RapportoDiLavoro.objects.filter(tredicesima=True).update(tredicesima_rateo_mensile_in_imponibile=True)
    RapportoDiLavoro.objects.filter(quattordicesima=True).update(quattordicesima_rateo_mensile_in_imponibile=True)
    PropostaAssunzione.objects.filter(tredicesima=True).update(tredicesima_rateo_mensile_in_imponibile=True)
    PropostaAssunzione.objects.filter(quattordicesima=True).update(quattordicesima_rateo_mensile_in_imponibile=True)


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0038_mappatura_voce_motore'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportodilavoro',
            name='quattordicesima_rateo_mensile_in_imponibile',
            field=models.BooleanField(
                default=False,
                help_text='Come per la 13ª: solo se la quota mensile è effettivamente in busta e imponibile mensilmente.',
                verbose_name='14ª: quota mensile in busta (base INPS/IRPEF/INAIL)',
            ),
        ),
        migrations.AddField(
            model_name='rapportodilavoro',
            name='tredicesima_rateo_mensile_in_imponibile',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'Se attivo, la quota 1/12 erogata ogni mese in cedolino concorre alla base contributiva e fiscale mensile. '
                    'Se disattivo, il rateo resta solo accantonamento / riferimento (es. pagamento a dicembre).'
                ),
                verbose_name='13ª: quota mensile in busta (base INPS/IRPEF/INAIL)',
            ),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='quattordicesima_rateo_mensile_in_imponibile',
            field=models.BooleanField(
                default=False,
                help_text='Come per la 13ª: attivare solo se la 14ª è rateizzata in busta ogni mese.',
                verbose_name='14ª: quota mensile in busta (imponibile mensile)',
            ),
        ),
        migrations.AddField(
            model_name='propostaassunzione',
            name='tredicesima_rateo_mensile_in_imponibile',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'Se vero, la quota 1/12 mensile è in cedolino e concorre a INPS/IRPEF/INAIL del mese; '
                    'altrimenti è solo accantonamento teorico.'
                ),
                verbose_name='13ª: quota mensile in busta (imponibile mensile)',
            ),
        ),
        migrations.RunPython(forwards_set_ratei_imponibile_da_contratto, backwards_noop),
    ]
