# Generated by Django 6.0.3 on 2026-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0042_alter_simulazioneorganico_mese_riferimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostaassunzione',
            name='superminimo_mensile',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Misura fissa concordata di riferimento a tempo pieno (€/mese, imponibile). È la fonte dati per busta e simulatore: il coefficiente part-time del tipo contratto determina l’importo mensile in cedolino (× % PT) e la quota €/h sul divisore CCNL. Compilare sul contratto e sulla proposta quando previsto. Concorre a 13ª/14ª, TFR, INPS, ferie/permessi e trattamento economico; non è bonus una tantum.', max_digits=10, verbose_name='Superminimo (rif. tempo pieno, €/mese)'),
        ),
        migrations.AlterField(
            model_name='rapportodilavoro',
            name='superminimo_mensile',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Misura fissa concordata di riferimento a tempo pieno (€/mese, imponibile). È la fonte dati per busta e simulatore: il coefficiente part-time del tipo contratto determina l’importo mensile in cedolino (× % PT) e la quota €/h sul divisore CCNL. Compilare sul contratto e sulla proposta quando previsto. Concorre a 13ª/14ª, TFR, INPS, ferie/permessi e trattamento economico; non è bonus una tantum.', max_digits=10, verbose_name='Superminimo (rif. tempo pieno, €/mese)'),
        ),
    ]
