# Generated by Django 5.2.14 on 2026-05-17 11:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapporto_di_lavoro', '0043_superminimo_help_rif_ft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendumcontrattuale',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='addizionalecomunale',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='addizionaleregionale',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bonusfiscale',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calendariolavoromensile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calendariopresenzedipendente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ccnl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chiusuraaziendale',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='decontribuzioneparametro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detrazionelavorodipendente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='festivitacalendario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='franchigiasogliavoce',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fringebenefitsoglia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inailparametro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mansione',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mansionelivelloccnl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mappaturavocemotore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modulocontrattuale',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametroccnlturismo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametrocontributi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametromaggiorazione',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametroorario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametroratei',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametroscattiannuali',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametrovoceretributiva',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='propostaassunzione',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rapportodilavoro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regolanormativaccnl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riepilogomensiledipendente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ruoloorganico2026',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scaglioneirpef',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simulazioneorganico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simulazionepagasalvata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simulazionevoceretributivaore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testmotorepaga',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipoassenza',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipocontratto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='validazioneorario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voceretributiva',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EventoContrattuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('promozione', 'Promozione'), ('aspettativa', 'Aspettativa'), ('licenziamento', 'Licenziamento'), ('dimissioni', 'Dimissioni')], max_length=30)),
                ('data_evento', models.DateField()),
                ('nuovo_livello', models.CharField(blank=True, max_length=50)),
                ('nuovo_stipendio_lordo_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('giorni_ferie_non_godute', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('giorni_permessi_non_goduti', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('giorni_preavviso', models.IntegerField(blank=True, null=True)),
                ('valore_tfr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parametri_specifici', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('rapporto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_contrattuali', to='rapporto_di_lavoro.rapportodilavoro')),
            ],
            options={
                'verbose_name': 'Evento contrattuale',
                'verbose_name_plural': 'Eventi contrattuali',
                'ordering': ['-data_evento', 'rapporto'],
            },
        ),
        migrations.CreateModel(
            name='LivelloCCNL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello', models.CharField(max_length=50)),
                ('minimo_tabellare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inizio', models.DateField(default=datetime.date.today)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('ccnl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livelli_ccnl', to='rapporto_di_lavoro.ccnl')),
            ],
            options={
                'verbose_name': 'Livello CCNL',
                'verbose_name_plural': 'Livelli CCNL',
                'ordering': ['ccnl', 'livello', '-data_inizio'],
                'unique_together': {('ccnl', 'livello', 'data_inizio')},
            },
        ),
        migrations.CreateModel(
            name='Transizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('nuovo_livello', models.CharField(max_length=50)),
                ('nuovo_stipendio_lordo_mensile', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nuovo_ore_settimanali', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('rapporto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transizioni', to='rapporto_di_lavoro.rapportodilavoro')),
            ],
            options={
                'verbose_name': 'Transizione contrattuale',
                'verbose_name_plural': 'Transizioni contrattuali',
                'ordering': ['-data_inizio', 'rapporto'],
                'unique_together': {('rapporto', 'data_inizio')},
            },
        ),
    ]
