# Generated by Django 6.0.3 on 2026-03-05 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0001_initial'),
        ('documenti', '0001_initial'),
        ('presenze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoStorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('assunzione', 'Assunzione'), ('variazione', 'Variazione'), ('documento', 'Documento'), ('presenza', 'Presenza'), ('richiesta', 'Richiesta'), ('cessazione', 'Cessazione'), ('altro', 'Altro')], max_length=20)),
                ('data_evento', models.DateTimeField()),
                ('descrizione', models.TextField(blank=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.azienda')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.dipendente')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documenti.documento')),
                ('presenza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presenze.presenza')),
            ],
        ),
    ]
