# Generated by Django 6.0.3 on 2026-03-05 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0001_initial'),
        ('storico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroPaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese', models.IntegerField()),
                ('anno', models.IntegerField()),
                ('stipendio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contributi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trattenute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.azienda')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.dipendente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_accesso', models.DateTimeField(auto_now_add=True)),
                ('descrizione', models.TextField()),
                ('azienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.azienda')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoricoAccessi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_azione', models.DateTimeField(auto_now_add=True)),
                ('azione', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
