# Generated by Django 6.0.3 on 2026-04-05 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0006_azienda_sede_lavorativa_indirizzo_and_more'),
        ('storico', '0002_libropaga_registrounico_storicoaccessi'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroPagaStorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio_rapporto', models.DateField()),
                ('data_fine_rapporto', models.DateField(blank=True, null=True)),
                ('periodo_riferimento', models.CharField(help_text='Formato MM/YYYY', max_length=7)),
                ('data_pagamento', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordinamento', models.PositiveIntegerField(default=0, help_text='Riordino manuale cronologico')),
                ('note', models.TextField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('modificato_il', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.azienda')),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libri_paga_storici', to='anagrafiche.dipendente')),
            ],
            options={
                'verbose_name': 'Voce libro paga storico',
                'verbose_name_plural': 'Libro paga storico',
                'ordering': ['dipendente', 'ordinamento', 'data_pagamento'],
            },
        ),
    ]
