# Generated by Django 6.0.3 on 2026-04-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storico', '0003_libropagastorico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libropagastorico',
            options={'ordering': ['dipendente', 'ordinamento', 'data_pagamento'], 'verbose_name': 'Voce libro paga', 'verbose_name_plural': 'Libro Unico del Lavoro'},
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='addizionali',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Addizionali regionali/comunali (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='altre_trattenute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altre trattenute (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='costo_azienda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo totale azienda (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='fonte_dati',
            field=models.CharField(choices=[('simulazione', 'Simulazione paga'), ('documento', 'Documento busta paga'), ('manuale', 'Inserimento manuale'), ('importazione', 'Importazione dati storici')], default='manuale', max_length=20, verbose_name='Fonte dati'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='inail_azienda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='INAIL c/azienda (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='indennita_accessorie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Indennità e accessori (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='inps_azienda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='INPS c/azienda (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='inps_dipendente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='INPS c/dipendente (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='irpef',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IRPEF trattenuta (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='livello_ccnl',
            field=models.CharField(blank=True, max_length=50, verbose_name='Livello CCNL'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='lordo_mensile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lordo imponibile (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='ore_assenza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ore assenza/ferie/ROL'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='ore_ordinarie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ore ordinarie'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='ore_straordinario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ore straordinario'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='qualifica',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qualifica'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='rateo_13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rateo 13ª (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='rateo_14',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rateo 14ª (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='retribuzione_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retribuzione base (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='tfr_mensile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TFR accantonato (€)'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='tipo_contratto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo contratto'),
        ),
        migrations.AddField(
            model_name='libropagastorico',
            name='trattamento_integrativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Trattamento integrativo/Bonus (€)'),
        ),
        migrations.AlterField(
            model_name='libropagastorico',
            name='data_fine_rapporto',
            field=models.DateField(blank=True, null=True, verbose_name='Fine rapporto'),
        ),
        migrations.AlterField(
            model_name='libropagastorico',
            name='data_inizio_rapporto',
            field=models.DateField(verbose_name='Inizio rapporto'),
        ),
        migrations.AlterField(
            model_name='libropagastorico',
            name='data_pagamento',
            field=models.DateField(verbose_name='Data pagamento'),
        ),
        migrations.AlterField(
            model_name='libropagastorico',
            name='importo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Netto erogato (€)'),
        ),
        migrations.AlterField(
            model_name='libropagastorico',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='libropagastorico',
            name='periodo_riferimento',
            field=models.CharField(help_text='Formato MM/YYYY', max_length=7, verbose_name='Periodo'),
        ),
    ]
